from backend.repositories.repositories import (
                                               agent_repo,
                                               api_key_repo,
                                               audit_repo,
                                               billing_repo,
                                               call_repo,
                                               campaign_repo,
                                               contact_repo,
                                               integration_repo,
                                               knowledge_repo,
                                               notification_repo,
                                               org_repo,
                                               phone_repo,
                                               settings_repo,
                                               user_repo,
                                               workflow_repo,
)

__all__ = [
                                               "agent_repo",
                                               "api_key_repo",
                                               "audit_repo",
                                               "billing_repo",
                                               "call_repo",
                                               "campaign_repo",
                                               "contact_repo",
                                               "integration_repo",
                                               "knowledge_repo",
                                               "notification_repo",
                                               "org_repo",
                                               "phone_repo",
                                               "settings_repo",
                                               "user_repo",
                                               "workflow_repo",
]
