import json
import os
import sys
import uuid

sys.path.insert(0, os.getcwd())
from backend.database.session import SessionLocal
from backend.models.models import ProviderCredential, User
from backend.utils.crypto import encrypt_secret

def seed_telephony_providers():
    db = SessionLocal()
    users = db.query(User).all()
    if not users:
        print("No users found in DB.")
        db.close()
        return

    # Find primary admin user and organization
    admin_user = next((u for u in users if u.email == 'admin@nexus.ai'), users[0])
    org_id = admin_user.organization_id
    user_id = admin_user.id
    print(f"Seeding telephony providers for user={admin_user.email}, org={org_id}")

    CARRIERS_DATA = [
        # --- 1. GLOBAL CLOUD VOICE APIS ---
        {
            "id": "tel_twilio_01",
            "preset_key": "twilio",
            "name": "Twilio Cloud Telephony",
            "display_name": "Twilio Primary Cloud Carrier",
            "provider_type": "Cloud Telephony",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": True,
            "account_sid": "ACa9b8c7d6e5f41234567890abcdef12",
            "auth_token": "••••••••••••••••",
            "api_key": "+18005550199",
            "api_secret": "AP_twml_voice_dispatcher",
            "base_url": "https://api.twilio.com/2010-04-01",
            "api_version": "2010-04-01",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/twilio",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.014",
            "inbound_cost": "$0.0085",
            "did_monthly_cost": "$1.00",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "$142.50",
            "latency": "18ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": True, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Tier-1 global voice carrier with elastic SIP trunking, call recording, and SMS delivery.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_plivo_02",
            "preset_key": "plivo",
            "name": "Plivo Voice API Gateway",
            "display_name": "Plivo Global High-Speed Voice",
            "provider_type": "Cloud Telephony",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "MAMDYXNDEZMTCZNDG2NT",
            "auth_token": "••••••••••••••••",
            "api_key": "+14155550144",
            "api_secret": "app_plivo_voice_xml",
            "base_url": "https://api.plivo.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/plivo",
            "pricing_mode": "Free Trial",
            "cost_per_min": "$0.012",
            "inbound_cost": "$0.007",
            "did_monthly_cost": "$0.80",
            "trial_credits": "$15.00",
            "trial_minutes": "500 mins",
            "billing_interval": "Trial Sandbox Mode",
            "live_balance": "$15.00 (Trial Active)",
            "latency": "15ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Direct low-latency carrier with instant call initiation and XML voice response processing.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_vonage_03",
            "preset_key": "vonage",
            "name": "Vonage (Nexmo) Voice API",
            "display_name": "Vonage Enterprise Global Voice",
            "provider_type": "Cloud Telephony",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "vonage_app_8b72c91d",
            "auth_token": "••••••••••••••••",
            "api_key": "vonage_api_key_778",
            "api_secret": "vonage_secret_private_key",
            "base_url": "https://api.nexmo.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/vonage",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.013",
            "inbound_cost": "$0.008",
            "did_monthly_cost": "$0.90",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "$78.20",
            "latency": "22ms",
            "sla_health": "99.98%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": True, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Enterprise NCCO voice routing, programmable call control, and global DID numbers.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_sinch_04",
            "preset_key": "sinch",
            "name": "Sinch Voice API",
            "display_name": "Sinch Telecom Cloud Gateway",
            "provider_type": "Cloud Telephony",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "sinch_proj_44a8c9b2",
            "auth_token": "••••••••••••••••",
            "api_key": "sinch_key_prod_899",
            "api_secret": "sinch_secret_prod_key",
            "base_url": "https://calling.api.sinch.com/calling/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/sinch",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.011",
            "inbound_cost": "$0.006",
            "did_monthly_cost": "$0.85",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "$92.00",
            "latency": "19ms",
            "sla_health": "99.97%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Global Tier-1 voice carrier with seamless PSTN termination and elastic WebRTC connectivity.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_bandwidth_05",
            "preset_key": "bandwidth",
            "name": "Bandwidth Voice Gateway",
            "display_name": "Bandwidth Direct IP Carrier",
            "provider_type": "Cloud Telephony",
            "country": "United States (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "bw_acc_99218274",
            "auth_token": "••••••••••••••••",
            "api_key": "bw_user_nexus_api",
            "api_secret": "bw_app_voice_bridge",
            "base_url": "https://voice.bandwidth.com/api/v2",
            "api_version": "v2",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/bandwidth",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.009",
            "inbound_cost": "$0.004",
            "did_monthly_cost": "$0.50",
            "billing_interval": "6s/6s (Fractional)",
            "live_balance": "$310.00",
            "latency": "12ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": True, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Nationwide direct IP carrier with sub-cent wholesale rates and fractional 6s billing.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_signalwire_06",
            "preset_key": "signalwire",
            "name": "SignalWire Voice API",
            "display_name": "SignalWire Cloud Infrastructure",
            "provider_type": "Cloud Telephony",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "signalwire_proj_091823",
            "auth_token": "••••••••••••••••",
            "api_key": "nexuscall-space.signalwire.com",
            "api_secret": "sw_sip_dispatcher_token",
            "base_url": "https://nexuscall-space.signalwire.com/api/laml/2010-04-01",
            "api_version": "2010-04-01",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/signalwire",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.0095",
            "inbound_cost": "$0.005",
            "did_monthly_cost": "$0.70",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "$65.50",
            "latency": "16ms",
            "sla_health": "99.98%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Advanced FreeSWITCH-powered cloud voice engine with LaML compatibility.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_aws_chime_07",
            "preset_key": "aws_chime",
            "name": "Amazon Chime SDK Voice",
            "display_name": "AWS Cloud PSTN Audio",
            "provider_type": "Cloud Telephony",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "AKIAIOSFODNN7EXAMPLE",
            "auth_token": "••••••••••••••••",
            "api_key": "us-east-1",
            "api_secret": "sma_01829384756",
            "base_url": "https://voice.chime.aws.amazon.com",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/aws-chime",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.0035",
            "inbound_cost": "$0.0022",
            "did_monthly_cost": "$1.00",
            "billing_interval": "1s/1s (Per-Second)",
            "live_balance": "$180.00",
            "latency": "11ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Ultra-low cost AWS PSTN audio infrastructure with per-second billing and SIP media applications.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_azure_acs_08",
            "preset_key": "azure_acs",
            "name": "Azure Communication Services",
            "display_name": "Microsoft Azure Voice Gateway",
            "provider_type": "Cloud Telephony",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "https://nexus-voice.communication.azure.com",
            "auth_token": "••••••••••••••••",
            "api_key": "+18005550188",
            "api_secret": "azure_voice_app_sub",
            "base_url": "https://nexus-voice.communication.azure.com",
            "api_version": "2023-01-15-preview",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/azure-acs",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.004",
            "inbound_cost": "$0.003",
            "did_monthly_cost": "$1.00",
            "billing_interval": "1s/1s (Per-Second)",
            "live_balance": "$220.00",
            "latency": "14ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Enterprise Microsoft Azure cloud calling with direct PSTN termination and Microsoft Teams integration.",
            "scope": "Global Workspace"
        },

        # --- 2. INDIAN & REGIONAL TELECOM & DID GATEWAYS ---
        {
            "id": "tel_exotel_09",
            "preset_key": "exotel",
            "name": "Exotel India Telecom Gateway",
            "display_name": "Exotel Primary DID Carrier",
            "provider_type": "DID Provider",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "nexuscall_exotel_in",
            "auth_token": "••••••••••••••••",
            "api_key": "api_key_exotel_9901",
            "api_secret": "08047192800",
            "base_url": "https://api.exotel.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/exotel",
            "pricing_mode": "Paid",
            "cost_per_min": "₹0.70",
            "inbound_cost": "₹0.40",
            "did_monthly_cost": "₹500.00",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "₹4,200.00",
            "latency": "24ms",
            "sla_health": "99.95%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": False, "caller_id": True, "sip": False},
            "description": "TRAI compliant telecom carrier for Indian domestic calling campaigns and virtual toll-free DIDs.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_tata_smartflo_10",
            "preset_key": "tata_smartflo",
            "name": "Tata Smartflo (TTBS)",
            "display_name": "Tata Tele Business Smartflo",
            "provider_type": "DID Provider",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "smartflo.tatateleservices.com",
            "auth_token": "••••••••••••••••",
            "api_key": "cust_key_tata_8819",
            "api_secret": "18002090123",
            "base_url": "https://api-smartflo.tatateleservices.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/tata-smartflo",
            "pricing_mode": "Paid",
            "cost_per_min": "₹0.65",
            "inbound_cost": "₹0.35",
            "did_monthly_cost": "₹450.00",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "₹6,800.00",
            "latency": "20ms",
            "sla_health": "99.97%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Tata Tele Business Services enterprise cloud voice platform with multi-channel DID routing.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_airtel_iq_11",
            "preset_key": "airtel_iq",
            "name": "Airtel IQ Cloud Voice",
            "display_name": "Bharti Airtel Enterprise Cloud",
            "provider_type": "DID Provider",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "airtel_app_0091823",
            "auth_token": "••••••••••••••••",
            "api_key": "airtel_cust_771",
            "api_secret": "01140506070",
            "base_url": "https://api.airteliq.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/airtel-iq",
            "pricing_mode": "Paid",
            "cost_per_min": "₹0.60",
            "inbound_cost": "₹0.30",
            "did_monthly_cost": "₹400.00",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "₹5,500.00",
            "latency": "18ms",
            "sla_health": "99.98%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "High-speed Indian telecom gateway from Bharti Airtel for direct programmatic telephony.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_jio_enterprise_12",
            "preset_key": "jio_enterprise",
            "name": "Jio Enterprise SIP Gateway",
            "display_name": "Reliance Jio 5G SIP Trunk",
            "provider_type": "DID Provider",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "jio_sip.reliance.in",
            "auth_token": "••••••••••••••••",
            "api_key": "jio_sip_peer_4001",
            "api_secret": "02269988776",
            "base_url": "https://sip.jio.com/api/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/jio",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "₹0.00 (Unlimited Bundle)",
            "inbound_cost": "₹0.00 (Unlimited Bundle)",
            "did_monthly_cost": "₹0.00 (Included)",
            "flat_monthly_rate": "₹2,999 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "Unlimited Corporate Pack",
            "latency": "16ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Fixed monthly unlimited enterprise SIP trunking over Jio 5G VoLTE fiber backbone.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_knowlarity_13",
            "preset_key": "knowlarity",
            "name": "Knowlarity Super Receptionist",
            "display_name": "Knowlarity Virtual IVR DID",
            "provider_type": "DID Provider",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "sr_channel_knowlarity_01",
            "auth_token": "••••••••••••••••",
            "api_key": "sr_api_key_8821",
            "api_secret": "01244005500",
            "base_url": "https://api.knowlarity.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/knowlarity",
            "pricing_mode": "Paid",
            "cost_per_min": "₹0.85",
            "inbound_cost": "₹0.50",
            "did_monthly_cost": "₹750.00",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "₹3,400.00",
            "latency": "26ms",
            "sla_health": "99.94%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": False, "caller_id": True, "sip": False},
            "description": "Automated virtual receptionist IVR and call dispatch for inbound Indian business queries.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_myoperator_14",
            "preset_key": "myoperator",
            "name": "MyOperator Voice Gateway",
            "display_name": "MyOperator Cloud IVR DID",
            "provider_type": "DID Provider",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "myop_acc_901823",
            "auth_token": "••••••••••••••••",
            "api_key": "myop_token_auth_882",
            "api_secret": "01139585858",
            "base_url": "https://api.myoperator.co/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/myoperator",
            "pricing_mode": "Free Trial",
            "cost_per_min": "₹0.75",
            "inbound_cost": "₹0.45",
            "did_monthly_cost": "₹600.00",
            "trial_credits": "₹1,000.00",
            "trial_minutes": "500 mins",
            "billing_interval": "Trial Sandbox Mode",
            "live_balance": "₹1,000.00 (Trial Active)",
            "latency": "25ms",
            "sla_health": "99.95%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": False, "caller_id": True, "sip": False},
            "description": "Indian virtual call management, smart IVR flow routing, and customer callback campaigns.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_servetel_15",
            "preset_key": "servetel",
            "name": "Servetel Cloud Telephony",
            "display_name": "Servetel Toll-Free & DID",
            "provider_type": "DID Provider",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "servetel_org_7719",
            "auth_token": "••••••••••••••••",
            "api_key": "srv_key_voice_991",
            "api_secret": "18001200123",
            "base_url": "https://api.servetel.in/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/servetel",
            "pricing_mode": "Paid",
            "cost_per_min": "₹0.70",
            "inbound_cost": "₹0.40",
            "did_monthly_cost": "₹500.00",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "₹2,900.00",
            "latency": "22ms",
            "sla_health": "99.96%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": False},
            "description": "Reliable Indian domestic cloud telephony and 1800 toll-free customer support lines.",
            "scope": "Global Workspace"
        },

        # --- 3. DIRECT SIP TRUNKS & WHOLESALE ---
        {
            "id": "tel_telnyx_16",
            "preset_key": "telnyx",
            "name": "Telnyx Elastic SIP Trunk",
            "display_name": "Telnyx High-Capacity Direct SIP",
            "provider_type": "SIP Carrier",
            "country": "Global International PSTN",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "KEY01829384756abcdef",
            "auth_token": "••••••••••••••••",
            "api_key": "sip.telnyx.com",
            "api_secret": "100 Channels Elastic",
            "base_url": "https://api.telnyx.com/v2",
            "api_version": "v2",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/telnyx",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.007",
            "inbound_cost": "$0.005",
            "did_monthly_cost": "$0.85",
            "billing_interval": "1s/1s (Per-Second)",
            "live_balance": "$85.00",
            "latency": "14ms",
            "sla_health": "99.98%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Direct multi-cloud carrier routing with lowest latency and HD Opus voice support.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_commio_17",
            "preset_key": "commio",
            "name": "Commio (ThinQ) Direct SIP",
            "display_name": "Commio LCR Voice Routing",
            "provider_type": "SIP Carrier",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "commio_acc_90812",
            "auth_token": "••••••••••••••••",
            "api_key": "sip.thinq.com",
            "api_secret": "commio_lcr_profile",
            "base_url": "https://api.thinq.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/commio",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.006",
            "inbound_cost": "$0.0035",
            "did_monthly_cost": "$0.50",
            "billing_interval": "6s/6s (Fractional)",
            "live_balance": "$150.00",
            "latency": "15ms",
            "sla_health": "99.98%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Multi-carrier wholesale voice routing with automated Least Cost Routing (LCR) engine.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_flowroute_18",
            "preset_key": "flowroute",
            "name": "Flowroute SIP Trunk",
            "display_name": "Flowroute HyperNetwork SIP",
            "provider_type": "SIP Carrier",
            "country": "United States & Canada (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "flowroute_acc_88192",
            "auth_token": "••••••••••••••••",
            "api_key": "sip.flowroute.com",
            "api_secret": "flowroute_edge_route",
            "base_url": "https://api.flowroute.com/v2",
            "api_version": "v2",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/flowroute",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.008",
            "inbound_cost": "$0.0045",
            "did_monthly_cost": "$0.60",
            "billing_interval": "6s/6s (Fractional)",
            "live_balance": "$112.40",
            "latency": "17ms",
            "sla_health": "99.97%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "HyperNetwork direct carrier SIP interconnection with granular route selection.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_twilio_trunk_19",
            "preset_key": "twilio_trunk",
            "name": "Twilio Elastic SIP Trunking",
            "display_name": "Twilio Direct PBX Termination",
            "provider_type": "SIP Carrier",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "TK01829384756abcdef",
            "auth_token": "••••••••••••••••",
            "api_key": "nexuscall.pstn.twilio.com",
            "api_secret": "twilio_cred_list_01",
            "base_url": "https://trunking.twilio.com/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/twilio-trunk",
            "pricing_mode": "Paid",
            "cost_per_min": "$0.005",
            "inbound_cost": "$0.003",
            "did_monthly_cost": "$1.00",
            "billing_interval": "60s/60s (Standard)",
            "live_balance": "$95.00",
            "latency": "19ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Direct elastic SIP trunk termination connecting internal IP-PBX to global PSTN.",
            "scope": "Global Workspace"
        },

        # --- 4. PRIVATE ENTERPRISE PBX ---
        {
            "id": "tel_freepbx_20",
            "preset_key": "freepbx",
            "name": "FreePBX / PBXact Server",
            "display_name": "Internal FreePBX Softswitch",
            "provider_type": "Local/Custom Carrier",
            "country": "Private Enterprise Server (LAN/VPN)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "10.0.4.50:5060",
            "auth_token": "••••••••••••••••",
            "api_key": "nexus_trunk_peer",
            "api_secret": "5060 (UDP / TLS)",
            "base_url": "http://10.0.4.50/admin",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/freepbx",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.00 (Unlimited Bundle)",
            "inbound_cost": "$0.00 (Unlimited Bundle)",
            "did_monthly_cost": "$0.00 (Included)",
            "flat_monthly_rate": "$49.00 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "Self-Hosted PBX License",
            "latency": "3ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Open-source Asterisk FreePBX server running on internal server hardware with zero per-minute costs.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_asterisk_21",
            "preset_key": "asterisk",
            "name": "Asterisk PBX Core Server",
            "display_name": "Asterisk PJSIP Core Server",
            "provider_type": "Local/Custom Carrier",
            "country": "Private Enterprise Server (LAN/VPN)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "10.0.4.60:5060",
            "auth_token": "••••••••••••••••",
            "api_key": "pjsip_endpoint_nexus",
            "api_secret": "5060 (PJSIP Transport)",
            "base_url": "http://10.0.4.60:8088/ari",
            "api_version": "ari",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/asterisk",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.00 (Unlimited Bundle)",
            "inbound_cost": "$0.00 (Unlimited Bundle)",
            "did_monthly_cost": "$0.00 (Included)",
            "flat_monthly_rate": "$49.00 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "Self-Hosted PBX Engine",
            "latency": "2ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Direct Asterisk PJSIP / ARI REST trunk interconnect for real-time robotic calling pipelines.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_cisco_cucm_22",
            "preset_key": "cisco_cucm",
            "name": "Cisco CUCM Gateway",
            "display_name": "Cisco CallManager Trunk",
            "provider_type": "Local/Custom Carrier",
            "country": "Private Enterprise Server (LAN/VPN)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "10.0.10.100:5060",
            "auth_token": "••••••••••••••••",
            "api_key": "cisco_sip_trunk_profile",
            "api_secret": "5061 (TLS Secure)",
            "base_url": "https://10.0.10.100:8443/axl",
            "api_version": "axl",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/cisco",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.00 (Unlimited Bundle)",
            "inbound_cost": "$0.00 (Unlimited Bundle)",
            "did_monthly_cost": "$0.00 (Included)",
            "flat_monthly_rate": "$49.00 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "Enterprise Cisco Cluster",
            "latency": "4ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Cisco Unified Communications Manager enterprise cluster SIP trunk connection.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_threecx_23",
            "preset_key": "threecx",
            "name": "3CX Phone System IP Gateway",
            "display_name": "3CX VoIP Phone System",
            "provider_type": "Local/Custom Carrier",
            "country": "Private Enterprise Server (LAN/VPN)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "pbx.company.3cx.us:5060",
            "auth_token": "••••••••••••••••",
            "api_key": "ext_nexus_1001",
            "api_secret": "5060 (3CX Gateway)",
            "base_url": "https://pbx.company.3cx.us:5001/api",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/3cx",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.00 (Unlimited Bundle)",
            "inbound_cost": "$0.00 (Unlimited Bundle)",
            "did_monthly_cost": "$0.00 (Included)",
            "flat_monthly_rate": "$49.00 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "3CX Enterprise Dedicated",
            "latency": "5ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "3CX enterprise software PBX bridge with multi-extension routing and ring groups.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_kamailio_24",
            "preset_key": "kamailio",
            "name": "Kamailio SIP Proxy Engine",
            "display_name": "Kamailio High-Throughput Proxy",
            "provider_type": "Local/Custom Carrier",
            "country": "Private Enterprise Server (LAN/VPN)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "10.0.4.70:5060",
            "auth_token": "••••••••••••••••",
            "api_key": "dispatcher_group_1",
            "api_secret": "5060 (UDP/TCP/TLS)",
            "base_url": "http://10.0.4.70:5060/rpc",
            "api_version": "rpc",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/kamailio",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.00 (Unlimited Bundle)",
            "inbound_cost": "$0.00 (Unlimited Bundle)",
            "did_monthly_cost": "$0.00 (Included)",
            "flat_monthly_rate": "$49.00 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "High-Volume SIP Matrix",
            "latency": "1ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": False, "transfer": True, "forwarding": True, "conference": False, "caller_id": True, "sip": True},
            "description": "Carrier-grade SIP proxy routing engine handling up to 10,000 concurrent SIP calls.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_freeswitch_25",
            "preset_key": "freeswitch",
            "name": "FreeSWITCH PBX Gateway",
            "display_name": "FreeSWITCH Realtime Engine",
            "provider_type": "Local/Custom Carrier",
            "country": "Private Enterprise Server (LAN/VPN)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "10.0.4.80:5060",
            "auth_token": "••••••••••••••••",
            "api_key": "esl_socket_nexus",
            "api_secret": "8021 (ESL Event Socket)",
            "base_url": "http://10.0.4.80:8080",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/freeswitch",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.00 (Unlimited Bundle)",
            "inbound_cost": "$0.00 (Unlimited Bundle)",
            "did_monthly_cost": "$0.00 (Included)",
            "flat_monthly_rate": "$49.00 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "FreeSWITCH Core Node",
            "latency": "2ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "High-performance real-time media switching and ESL event socket integration.",
            "scope": "Global Workspace"
        },

        # --- 5. LOCAL GSM & MOBILE SIM GATEWAYS ---
        {
            "id": "tel_gsm_26",
            "preset_key": "gsm",
            "name": "Android GSM Gateway App",
            "display_name": "Companion Android SIM (Zero Cost)",
            "provider_type": "GSM Carrier",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "192.168.1.140:8080",
            "auth_token": "••••••••",
            "api_key": "SIM 1 (Jio Unlimited 5G)",
            "api_secret": "Samsung Galaxy S22 Gateway",
            "base_url": "http://192.168.1.140:8080",
            "api_version": "v1",
            "webhook_url": "http://192.168.1.140:8080/events",
            "pricing_mode": "Free",
            "cost_per_min": "₹0.00 / min (Free)",
            "inbound_cost": "₹0.00 / min (Free)",
            "did_monthly_cost": "₹0.00 (Zero Charge)",
            "billing_interval": "Zero Platform Charge (Pass-Through)",
            "live_balance": "Unlimited SIM Calling Pack",
            "latency": "8ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Zero-cost companion Android smartphone SIM gateway using local unlimited carrier talk plans.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_dinstar_27",
            "preset_key": "dinstar_gsm",
            "name": "Dinstar / GoIP GSM Gateway",
            "display_name": "Dinstar 16-Channel SIM Bank",
            "provider_type": "GSM Carrier",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "192.168.1.200:5060",
            "auth_token": "••••••••",
            "api_key": "dinstar_admin_user",
            "api_secret": "Slot 1-16 Multi-SIM Array",
            "base_url": "http://192.168.1.200",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/dinstar",
            "pricing_mode": "Free",
            "cost_per_min": "₹0.00 / min (Free)",
            "inbound_cost": "₹0.00 / min (Free)",
            "did_monthly_cost": "₹0.00 (Zero Charge)",
            "billing_interval": "Zero Platform Charge (Pass-Through)",
            "live_balance": "16 Local SIMs Active",
            "latency": "9ms",
            "sla_health": "99.98%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": False, "caller_id": True, "sip": True},
            "description": "Enterprise 16-channel hardware VoIP-to-GSM SIM bank converting SIP calls into cellular carrier calls.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_usb_modem_28",
            "preset_key": "usb_modem",
            "name": "USB 4G/LTE Modem Dongle",
            "display_name": "Huawei LTE USB Modem",
            "provider_type": "GSM Carrier",
            "country": "India (+91 PSTN)",
            "currency": "INR (₹)",
            "status": "Active",
            "is_default": False,
            "account_sid": "/dev/ttyUSB0",
            "auth_token": "••••",
            "api_key": "SIM Slot 1",
            "api_secret": "Huawei E3372 4G Dongle",
            "base_url": "http://localhost:8080/dongle",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/usb-modem",
            "pricing_mode": "Free",
            "cost_per_min": "₹0.00 / min (Free)",
            "inbound_cost": "₹0.00 / min (Free)",
            "did_monthly_cost": "₹0.00 (Zero Charge)",
            "billing_interval": "Zero Platform Charge (Pass-Through)",
            "live_balance": "Direct USB Dongle",
            "latency": "6ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": False, "forwarding": False, "conference": False, "caller_id": True, "sip": False},
            "description": "Physical 4G LTE USB modem attached directly to server for local SMS and direct voice calling.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_cloud_esim_29",
            "preset_key": "cloud_esim",
            "name": "Cloud eSIM Matrix Pool",
            "display_name": "Virtual eSIM Multi-Carrier Pool",
            "provider_type": "GSM Carrier",
            "country": "Global International PSTN",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "esim_pool_global_9901",
            "auth_token": "••••••••••••••••",
            "api_key": "eSIM Array Slot #4",
            "api_secret": "Global eSIM Matrix ID",
            "base_url": "https://api.esimmatrix.cloud/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/cloud-esim",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.00 (Unlimited Bundle)",
            "inbound_cost": "$0.00 (Unlimited Bundle)",
            "did_monthly_cost": "$0.00 (Included)",
            "flat_monthly_rate": "$29.00 / mo",
            "billing_interval": "Monthly Unlimited Subscription",
            "live_balance": "Virtual eSIM Cluster",
            "latency": "10ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Software-defined virtual eSIM calling array with on-demand roaming profiles across 140 countries.",
            "scope": "Global Workspace"
        },

        # --- 6. CUSTOM CARRIER INTEGRATIONS ---
        {
            "id": "tel_custom_30",
            "preset_key": "custom",
            "name": "Custom REST Voice API",
            "display_name": "Proprietary Enterprise Voice API",
            "provider_type": "Custom",
            "country": "United States & Global (+1)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "Bearer nex_custom_tok_9918237",
            "auth_token": "••••••••••••••••",
            "api_key": "X-Nexus-Auth-Key",
            "api_secret": "hmac_sha256_custom_secret",
            "base_url": "https://telephony.customcompany.internal/v1",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/custom-rest",
            "pricing_mode": "Custom",
            "cost_per_min": "$0.010",
            "inbound_cost": "$0.005",
            "did_monthly_cost": "$1.00",
            "custom_tier1_rate": "$0.010 / min (<10k mins)",
            "custom_tier2_rate": "$0.007 / min (>50k mins)",
            "min_monthly_commit": "$250.00",
            "billing_interval": "Negotiated Enterprise Rate Card",
            "live_balance": "$250.00 / mo Commit",
            "latency": "21ms",
            "sla_health": "99.95%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Proprietary REST API carrier with custom Bearer/HMAC headers and negotiated volume tiering.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_custom_sip_31",
            "preset_key": "custom_sip",
            "name": "Custom Private SIP Trunk",
            "display_name": "Custom Dedicated SIP Route",
            "provider_type": "Custom",
            "country": "Private Enterprise Server (LAN/VPN)",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "sip.customcarrier.net:5060",
            "auth_token": "••••••••••••••••",
            "api_key": "nexus_sip_peer_1",
            "api_secret": "UDP / TLS Port 5060",
            "base_url": "https://sip.customcarrier.net/api",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/custom-sip",
            "pricing_mode": "Flat-Rate Unlimited",
            "cost_per_min": "$0.004",
            "inbound_cost": "$0.002",
            "did_monthly_cost": "$0.00",
            "flat_monthly_rate": "$49.00 / mo",
            "billing_interval": "Direct SIP Interconnect",
            "live_balance": "Dedicated SIP Channel",
            "latency": "7ms",
            "sla_health": "99.99%",
            "capabilities": {"inbound": True, "outbound": True, "sms": False, "mms": False, "dtmf": True, "recording": True, "transfer": True, "forwarding": True, "conference": True, "caller_id": True, "sip": True},
            "description": "Custom SIP host with MD5 digest authentication, custom codecs, and SRTP transport.",
            "scope": "Global Workspace"
        },
        {
            "id": "tel_custom_webhook_32",
            "preset_key": "custom_webhook",
            "name": "Custom Webhook Call Dispatcher",
            "display_name": "HTTP Event Webhook Dispatcher",
            "provider_type": "Custom",
            "country": "Global International PSTN",
            "currency": "USD ($)",
            "status": "Active",
            "is_default": False,
            "account_sid": "https://dispatcher.internal.org/call",
            "auth_token": "••••••••••••••••",
            "api_key": "X-Signature-Sha256",
            "api_secret": "webhook_signing_secret_998",
            "base_url": "https://dispatcher.internal.org",
            "api_version": "v1",
            "webhook_url": "https://api.nexuscall.os/v1/webhooks/voice/custom-events",
            "pricing_mode": "Free",
            "cost_per_min": "$0.00 / min (Free)",
            "inbound_cost": "$0.00 / min (Free)",
            "did_monthly_cost": "$0.00 (Zero Charge)",
            "billing_interval": "Zero Platform Charge (Pass-Through)",
            "live_balance": "Event Webhook Queue",
            "latency": "13ms",
            "sla_health": "100%",
            "capabilities": {"inbound": True, "outbound": True, "sms": True, "mms": False, "dtmf": True, "recording": False, "transfer": True, "forwarding": True, "conference": False, "caller_id": True, "sip": False},
            "description": "Asynchronous HTTP Webhook call dispatcher sending signed JSON payload events to third-party endpoints.",
            "scope": "Global Workspace"
        }
    ]

    SIP_DATA = [
        {
            "id": "sip_twilio_01",
            "preset_key": "twilio_sip",
            "name": "Twilio Elastic SIP Trunk",
            "display_name": "Twilio Elastic SIP (Global PSTN)",
            "carrier": "Twilio Cloud Telephony",
            "direction": "Bidirectional",
            "sip_domain": "sip.nexuscall.pstn.twilio.com",
            "sip_host": "sip.pstn.twilio.com",
            "sip_port": "5060",
            "transport": "TLS Port 5061 (Encrypted)",
            "outbound_proxy": "",
            "username": "nexus_trunk_admin",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Registered (200 OK • 12ms)",
            "ip_whitelist": "54.172.60.0/23, 54.244.51.0/24",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "SRTP Mandatory (AES-128-GCM)",
            "cng_enabled": True,
            "concurrent_calls": "500 Channels",
            "cps_rate_limit": "50 CPS",
            "primary_carrier": "Twilio Cloud Telephony",
            "secondary_carrier": "Telnyx Private Cloud SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+1 (800) 555-0199",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Tier-1 global elastic SIP trunking with automated TLS and SRTP media stream encryption.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_telnyx_02",
            "preset_key": "telnyx_sip",
            "name": "Telnyx Private Cloud SIP Trunk",
            "display_name": "Telnyx Direct Interconnect",
            "carrier": "Telnyx Enterprise Voice",
            "direction": "Bidirectional",
            "sip_domain": "sip.telnyx.com",
            "sip_host": "sip.telnyx.com",
            "sip_port": "5061",
            "transport": "TLS Port 5061 (Encrypted)",
            "outbound_proxy": "",
            "username": "telnyx_voice_sub",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Connected (IP ACL • 16ms)",
            "ip_whitelist": "192.76.120.0/22, 64.16.240.0/21",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "SRTP Mandatory (AES-128-GCM)",
            "cng_enabled": True,
            "concurrent_calls": "1000 Channels",
            "cps_rate_limit": "100 CPS",
            "primary_carrier": "Telnyx Enterprise Voice",
            "secondary_carrier": "Twilio Elastic SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+1 (888) 555-0144",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Dedicated high-capacity IP-authenticated trunk for massive concurrent outbound AI dialer campaigns.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_airtel_03",
            "preset_key": "airtel_sip",
            "name": "Bharti Airtel IQ Direct SIP Interconnect",
            "display_name": "Airtel IQ Enterprise PSTN Trunk",
            "carrier": "Bharti Airtel IQ",
            "direction": "Bidirectional",
            "sip_domain": "sip.airteliq.com",
            "sip_host": "sip.airteliq.com",
            "sip_port": "5060",
            "transport": "UDP Port 5060 (Standard)",
            "outbound_proxy": "",
            "username": "airtel_iq_nexus_01",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Registered (200 OK • 8ms)",
            "ip_whitelist": "125.16.0.0/12, 182.79.0.0/16",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "Optional / Best-Effort",
            "cng_enabled": True,
            "concurrent_calls": "200 Channels",
            "cps_rate_limit": "25 CPS",
            "primary_carrier": "Bharti Airtel IQ",
            "secondary_carrier": "Tata Smartflo (TTBS) Enterprise SIP",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+91 11 4084 0000",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Certified Indian telecom carrier direct interconnect with zero-hop local PSTN routing and DLT compliance.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_tata_04",
            "preset_key": "tata_sip",
            "name": "Tata Smartflo (TTBS) Enterprise SIP",
            "display_name": "Tata Smartflo Enterprise SIP",
            "carrier": "Tata Tele Business Services",
            "direction": "Bidirectional",
            "sip_domain": "sip.tatasmartflo.com",
            "sip_host": "sip.tatasmartflo.com",
            "sip_port": "5060",
            "transport": "TLS Port 5061 (Encrypted)",
            "outbound_proxy": "",
            "username": "ttbs_smartflo_trunk",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Registered (200 OK • 10ms)",
            "ip_whitelist": "115.112.0.0/14, 121.240.0.0/13",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "SRTP Mandatory (AES-128-GCM)",
            "cng_enabled": True,
            "concurrent_calls": "300 Channels",
            "cps_rate_limit": "30 CPS",
            "primary_carrier": "Tata Tele Business Services",
            "secondary_carrier": "Bharti Airtel IQ Direct SIP Interconnect",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+91 22 6123 4567",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Tata Tele Business Services cloud communication suite with enterprise DID bundles and high SLA uptime.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_jio_05",
            "preset_key": "jio_sip",
            "name": "Reliance Jio Enterprise SIP Trunk",
            "display_name": "Reliance Jio 5G Enterprise SIP",
            "carrier": "Reliance Jio Infocomm",
            "direction": "Bidirectional",
            "sip_domain": "ims.jio.com",
            "sip_host": "sip.enterprise.jio.com",
            "sip_port": "5060",
            "transport": "UDP Port 5060 (Standard)",
            "outbound_proxy": "",
            "username": "jio_ent_sip_01",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Registered (200 OK • 6ms)",
            "ip_whitelist": "49.32.0.0/11, 157.32.0.0/11",
            "codecs": "📱 AMR-WB 16kHz VoLTE + G.711a",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "Optional / Best-Effort",
            "cng_enabled": True,
            "concurrent_calls": "500 Channels",
            "cps_rate_limit": "50 CPS",
            "primary_carrier": "Reliance Jio Infocomm",
            "secondary_carrier": "Bharti Airtel IQ Direct SIP Interconnect",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+91 22 7960 0000",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Native VoLTE and 5G NR voice interconnect across India with high packet delivery rate.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_freepbx_06",
            "preset_key": "freepbx_sip",
            "name": "FreePBX / Asterisk PBXact Softswitch",
            "display_name": "Internal FreePBX Softswitch",
            "carrier": "Internal PBX Server",
            "direction": "Bidirectional",
            "sip_domain": "pbx.local.internal",
            "sip_host": "192.168.1.200",
            "sip_port": "5060",
            "transport": "UDP Port 5060 (Standard)",
            "outbound_proxy": "",
            "username": "nexus_pjsip_trunk",
            "password": "••••••••••••••••",
            "auth_mode": "🔑 SIP Digest Authentication (Username & Password)",
            "registration_required": True,
            "registration_expires": "600s (10 Mins)",
            "registration_status": "Registered (200 OK • 2ms)",
            "ip_whitelist": "192.168.1.0/24, 10.0.0.0/16",
            "codecs": "⚡ Opus Fullband + G.711 u-law",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "Optional / Best-Effort",
            "cng_enabled": True,
            "concurrent_calls": "100 Channels",
            "cps_rate_limit": "20 CPS",
            "primary_carrier": "Internal PBX Server",
            "secondary_carrier": "Twilio Elastic SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "Remote-Party-ID (RPID)",
            "outbound_cli": "1001",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Open-source Asterisk FreePBX server running on internal server hardware with zero per-minute costs.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_cisco_07",
            "preset_key": "cisco_sip",
            "name": "Cisco CUCM / CallManager Enterprise",
            "display_name": "Cisco CallManager Trunk",
            "carrier": "Cisco Enterprise Cluster",
            "direction": "Bidirectional",
            "sip_domain": "cucm.company.internal",
            "sip_host": "10.0.10.100",
            "sip_port": "5060",
            "transport": "TLS Port 5061 (Encrypted)",
            "outbound_proxy": "",
            "username": "cisco_sip_profile",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Registered (200 OK • 4ms)",
            "ip_whitelist": "10.0.10.0/24",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "SRTP Mandatory (AES-128-GCM)",
            "cng_enabled": True,
            "concurrent_calls": "500 Channels",
            "cps_rate_limit": "40 CPS",
            "primary_carrier": "Cisco Enterprise Cluster",
            "secondary_carrier": "Twilio Elastic SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "Remote-Party-ID (RPID)",
            "outbound_cli": "+1 (800) 555-0100",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Cisco Unified Communications Manager enterprise cluster SIP trunk connection.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_threecx_08",
            "preset_key": "threecx_sip",
            "name": "3CX Phone System IP Gateway",
            "display_name": "3CX VoIP Phone System",
            "carrier": "3CX Cloud PBX",
            "direction": "Bidirectional",
            "sip_domain": "pbx.company.3cx.us",
            "sip_host": "pbx.company.3cx.us",
            "sip_port": "5060",
            "transport": "UDP Port 5060 (Standard)",
            "outbound_proxy": "",
            "username": "3cx_trunk_100",
            "password": "••••••••••••••••",
            "auth_mode": "🔑 SIP Digest Authentication (Username & Password)",
            "registration_required": True,
            "registration_expires": "600s (10 Mins)",
            "registration_status": "Registered (200 OK • 14ms)",
            "ip_whitelist": "0.0.0.0/0",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "Optional / Best-Effort",
            "cng_enabled": True,
            "concurrent_calls": "100 Channels",
            "cps_rate_limit": "15 CPS",
            "primary_carrier": "3CX Cloud PBX",
            "secondary_carrier": "Twilio Elastic SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+1 (800) 555-0300",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "3CX IP-PBX Gateway trunk bridging AI Voice Agents to human softphone extensions.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_kamailio_09",
            "preset_key": "kamailio_sip",
            "name": "Kamailio Carrier-Grade SIP Proxy",
            "display_name": "Kamailio High-Throughput Proxy",
            "carrier": "Kamailio SBC Cluster",
            "direction": "Bidirectional",
            "sip_domain": "sbc.carrier.internal",
            "sip_host": "10.0.4.150",
            "sip_port": "5060",
            "transport": "UDP Port 5060 (Standard)",
            "outbound_proxy": "proxy.sbc.internal:5060",
            "username": "kamailio_admin",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Connected (200 OK • 1ms)",
            "ip_whitelist": "10.0.4.0/24",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "Optional / Best-Effort",
            "cng_enabled": True,
            "concurrent_calls": "2000 Channels",
            "cps_rate_limit": "200 CPS",
            "primary_carrier": "Kamailio SBC Cluster",
            "secondary_carrier": "Telnyx Private Cloud SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+1 (800) 555-0400",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "High-throughput Kamailio Session Border Controller handling hundreds of thousands of concurrent calls.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_freeswitch_10",
            "preset_key": "freeswitch_sip",
            "name": "FreeSWITCH Realtime Core Engine",
            "display_name": "FreeSWITCH Realtime Core Engine",
            "carrier": "FreeSWITCH Softswitch Cluster",
            "direction": "Bidirectional",
            "sip_domain": "fs.nexuscall.internal",
            "sip_host": "10.0.4.160",
            "sip_port": "5060",
            "transport": "TLS Port 5061 (Encrypted)",
            "outbound_proxy": "",
            "username": "freeswitch_internal",
            "password": "••••••••••••••••",
            "auth_mode": "🔑 SIP Digest Authentication (Username & Password)",
            "registration_required": True,
            "registration_expires": "600s (10 Mins)",
            "registration_status": "Registered (200 OK • 2ms)",
            "ip_whitelist": "10.0.4.0/24",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "SRTP Mandatory (AES-128-GCM)",
            "cng_enabled": True,
            "concurrent_calls": "1000 Channels",
            "cps_rate_limit": "100 CPS",
            "primary_carrier": "FreeSWITCH Softswitch Cluster",
            "secondary_carrier": "Twilio Elastic SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+1 (800) 555-0500",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "High-performance FreeSWITCH voice core with mod_sofia and real-time robotic media pipelines.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_commio_11",
            "preset_key": "commio_sip",
            "name": "Commio (ThinQ) LCR Voice Network",
            "display_name": "Commio LCR Voice Routing",
            "carrier": "Commio (ThinQ)",
            "direction": "Bidirectional",
            "sip_domain": "sip.thinq.com",
            "sip_host": "sip.thinq.com",
            "sip_port": "5060",
            "transport": "UDP Port 5060 (Standard)",
            "outbound_proxy": "",
            "username": "commio_lcr_01",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Connected (IP ACL • 15ms)",
            "ip_whitelist": "192.240.150.0/24",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "Optional / Best-Effort",
            "cng_enabled": True,
            "concurrent_calls": "500 Channels",
            "cps_rate_limit": "50 CPS",
            "primary_carrier": "Commio (ThinQ)",
            "secondary_carrier": "Telnyx Private Cloud SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+1 (800) 555-0600",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "Least-Cost Routing multi-carrier wholesale SIP interconnect dynamically finding the cheapest path.",
            "scope": "Global Workspace"
        },
        {
            "id": "sip_flowroute_12",
            "preset_key": "flowroute_sip",
            "name": "Flowroute HyperNetwork Direct SIP",
            "display_name": "Flowroute HyperNetwork SIP",
            "carrier": "Flowroute Intrado",
            "direction": "Bidirectional",
            "sip_domain": "sip.flowroute.com",
            "sip_host": "sip.flowroute.com",
            "sip_port": "5060",
            "transport": "TLS Port 5061 (Encrypted)",
            "outbound_proxy": "",
            "username": "flowroute_nexus",
            "password": "••••••••••••••••",
            "auth_mode": "IP Access Control List (ACL / Whitelisting)",
            "registration_required": False,
            "registration_expires": "3600s",
            "registration_status": "Connected (IP ACL • 17ms)",
            "ip_whitelist": "216.115.69.0/24, 34.210.91.0/24",
            "codecs": "🎧 Opus HD + G.722 + PSTN",
            "dtmf_mode": "🔢 RFC 2833 / RFC 4733 (RTP Events)",
            "srtp": "SRTP Mandatory (AES-128-GCM)",
            "cng_enabled": True,
            "concurrent_calls": "300 Channels",
            "cps_rate_limit": "30 CPS",
            "primary_carrier": "Flowroute Intrado",
            "secondary_carrier": "Twilio Elastic SIP Trunk",
            "failover_enabled": True,
            "failover_trigger": "Immediate on SIP 5xx (500, 502, 503)",
            "caller_id_header": "P-Asserted-Identity (PAI)",
            "outbound_cli": "+1 (800) 555-0700",
            "nat_traversal": "STUN/TURN Assisted (25s Keepalive)",
            "status": "Active",
            "description": "HyperNetwork direct carrier SIP interconnection with granular route selection.",
            "scope": "Global Workspace"
        }
    ]

    GSM_DATA = [
        {
            "id": "gsm_s22_01",
            "name": "Samsung Galaxy S22 5G Gateway #1",
            "display_name": "Android Dual-SIM Gateway (Primary)",
            "device_type": "Android GSM Gateway",
            "location": "Headquarters Telecom Rack #1",
            "ip_host": "192.168.1.140:8080",
            "port": "8080",
            "protocol": "WebRTC / HTTP Direct",
            "sim_slots": "2 Slots",
            "active_sims": "2 Active SIMs",
            "sim_labels": "Slot 1: Jio 5G Unlimited (+91 98765 43210) • Slot 2: Airtel 5G Business (+91 91234 56789)",
            "signal_strength": "98% (-65 dBm 5G NR)",
            "battery_level": "100% (AC Powered)",
            "pricing_mode": "Free (Platform Zero-Charge)",
            "capabilities": "HD Voice, Automated SMS, DTMF, Call Recording",
            "registration_status": "Connected & Live (Latency: 8ms)",
            "status": "Active",
            "description": "Connected Android hardware gateway routing local domestic voice calls via unlimited carrier SIM bundles at zero platform charge.",
            "scope": "Global Workspace"
        },
        {
            "id": "gsm_dinstar_02",
            "name": "Dinstar UC2000-VG 32-Port GSM Box",
            "display_name": "Hardware Multi-Port SIM Bank",
            "device_type": "Multi-Port GSM Box",
            "location": "Datacenter Server Room C-4",
            "ip_host": "192.168.1.160:5060",
            "port": "1001",
            "protocol": "SIP / RTP (Port 5060)",
            "sim_slots": "32 Slots",
            "active_sims": "32 Active SIMs",
            "sim_labels": "32x SIM Pool (Auto-IMEI Anti-Blocking Rotation)",
            "signal_strength": "99% (Multi-Carrier Average)",
            "battery_level": "100% (Industrial UPS)",
            "pricing_mode": "Free (Platform Zero-Charge)",
            "capabilities": "32 Concurrent Channels, Auto-IMEI Rotation, SIP Trunking",
            "registration_status": "Connected & Live (32/32 SIMs Ready)",
            "status": "Active",
            "description": "Industrial 32-channel VoIP-to-GSM SIM box with intelligent round-robin and automatic IMEI anti-blocking rotation.",
            "scope": "Global Workspace"
        },
        {
            "id": "gsm_huawei_03",
            "name": "Huawei E3372h-320 USB 4G Dongle #1",
            "display_name": "Direct USB Cellular Modem",
            "device_type": "USB GSM Modem",
            "location": "Master Telephony Server USB Bus 1-2",
            "ip_host": "/dev/ttyUSB0 (Voice) • 127.0.0.1:9090",
            "port": "115200",
            "protocol": "AT Commands / chan_dongle",
            "sim_slots": "1 Slot",
            "active_sims": "1 Active SIM",
            "sim_labels": "Slot 1: Airtel 4G LTE VoLTE Dedicated Line (+91 99887 76655)",
            "signal_strength": "95% (-68 dBm 4G VoLTE)",
            "battery_level": "100% (USB Host Powered)",
            "pricing_mode": "Free (Platform Zero-Charge)",
            "capabilities": "Direct Raw AT Engine, 16kHz AMR-WB VoLTE Audio, SMS Gateway",
            "registration_status": "Connected & Live (Baud: 115200)",
            "status": "Active",
            "description": "Physical USB 4G cellular modem interfacing directly with chan_dongle and hardware serial AT commands.",
            "scope": "Global Workspace"
        },
        {
            "id": "gsm_teltonika_04",
            "name": "Teltonika RUT955 Industrial GSM Router",
            "display_name": "DIN-Rail IoT Cellular Router",
            "device_type": "Industrial GSM Router",
            "location": "Industrial Server Cabinet Rack #2",
            "ip_host": "192.168.1.170:8080",
            "port": "1883",
            "protocol": "MQTT / Modbus Telemetry",
            "sim_slots": "2 Slots",
            "active_sims": "2 Active SIMs",
            "sim_labels": "Slot 1: Jio 4G M2M Telemetry • Slot 2: Vi VoLTE Backup",
            "signal_strength": "94% (-72 dBm Industrial LTE)",
            "battery_level": "100% (DIN-Rail UPS)",
            "pricing_mode": "Free (Platform Zero-Charge)",
            "capabilities": "Dual-SIM Hot-Swap Failover, Modbus RS485, MQTT Heartbeat",
            "registration_status": "Connected & Live (MQTT Telemetry :1883)",
            "status": "Active",
            "description": "Rugged DIN-rail industrial cellular gateway featuring automated dual-SIM hot-swap failover and MQTT telemetry monitoring.",
            "scope": "Global Workspace"
        },
        {
            "id": "gsm_esim_05",
            "name": "Nexus Global eSIM Cloud Pool",
            "display_name": "Virtual eSIM Roaming Matrix",
            "device_type": "eSIM Cloud Gateway",
            "location": "Global Cloud Edge Infrastructure",
            "ip_host": "https://esim-edge.nexuscall.internal/v1",
            "port": "443",
            "protocol": "Cloud eSIM Webhook",
            "sim_slots": "8 Slots",
            "active_sims": "8 Active Profiles",
            "sim_labels": "Multi-IMSI Roaming (US, UK, IN, AE, SG Global Coverage)",
            "signal_strength": "100% (Virtual Cloud Pool)",
            "battery_level": "100% (Cloud Edge)",
            "pricing_mode": "Free (Platform Zero-Charge)",
            "capabilities": "Dynamic Multi-IMSI Carrier Switching, Zero Roaming Markup, Instant Provisioning",
            "registration_status": "Connected & Live (8 Virtual Profiles Ready)",
            "status": "Active",
            "description": "Software-defined virtual eSIM calling array with dynamic geo-routing across 190+ countries with zero platform surcharge.",
            "scope": "Global Workspace"
        }
    ]

    ROUTING_DATA = [
        {
            "id": "route_least_cost_01",
            "name": "Smart Least-Cost Outbound Routing",
            "display_name": "Least-Cost Outbound Dial Plan",
            "direction": "Outbound",
            "priority": "1",
            "match_conditions": "All Outbound Calling Campaigns • Domestic Numbers",
            "primary_route": "Samsung Galaxy S22 5G Gateway #1 (Free SIM)",
            "secondary_route": "Telnyx Elastic SIP Trunk ($0.007/min)",
            "failover_strategy": "Immediate on 5xx Error, SIM Busy, or Timeout (>4s)",
            "cost_preference": "Lowest Cost First (Zero-Charge SIM -> Cloud SIP)",
            "status": "Active",
            "description": "Automatically routes outbound calls through local Android SIM gateways first ($0.000 cost), falling back seamlessly to cloud SIP trunks if lines are occupied.",
            "scope": "Global Workspace"
        },
        {
            "id": "route_inbound_vip_02",
            "name": "Inbound VIP Support & DID Routing",
            "display_name": "Inbound Customer Routing Rule",
            "direction": "Inbound",
            "priority": "1",
            "match_conditions": "All Inbound Toll-Free & DID Numbers • Business Hours",
            "primary_route": "Twilio Cloud Telephony",
            "secondary_route": "Direct SIP Interconnect (Twilio)",
            "failover_strategy": "Instant Failover on SIP 486 Busy / Trunk Congestion",
            "cost_preference": "Highest Quality & Audio Fidelity",
            "status": "Active",
            "description": "Dispatches incoming customer calls directly into AI Voice Agents with sub-100ms response latency and HD Opus audio.",
            "scope": "Global Workspace"
        },
        {
            "id": "route_emergency_03",
            "name": "Emergency Triage & After-Hours Cascade",
            "display_name": "24/7 Escalation Routing",
            "direction": "Bidirectional",
            "priority": "1",
            "match_conditions": "After-Hours Calls & Urgent Inquiries",
            "primary_route": "Twilio Cloud Telephony",
            "secondary_route": "Samsung Galaxy S22 5G Gateway #1",
            "failover_strategy": "Simultaneous Ring (Parallel Cascade)",
            "cost_preference": "Maximum Reliability / Zero Dropped Calls",
            "status": "Active",
            "description": "High-availability emergency routing rule ensuring 100% call delivery with dual-carrier parallel failover.",
            "scope": "Global Workspace"
        }
    ]

    DISPOSITIONS_DATA = [
        {
            "id": "disp_booked_01",
            "name": "Appointment Booked & Confirmed",
            "code": "APPOINTMENT_BOOKED",
            "category": "Connected (Positive Outcome)",
            "color": "#10B981",
            "is_system": True,
            "auto_trigger": "Auto-sync to CRM Calendar & send SMS confirmation",
            "sentiment": "Positive (High Intent)",
            "status": "Active",
            "description": "Caller successfully scheduled and confirmed an appointment with the AI Voice Agent.",
            "scope": "Global Workspace"
        },
        {
            "id": "disp_interested_02",
            "name": "Connected & Interested (Hot Lead)",
            "code": "CONNECTED_HOT_LEAD",
            "category": "Connected (Sales Qualified)",
            "color": "#3B82F6",
            "is_system": True,
            "auto_trigger": "Assign high-priority lead to human SDR in CRM",
            "sentiment": "Positive (Warm Prospect)",
            "status": "Active",
            "description": "Prospect expressed strong purchase or booking interest; queued for priority follow-up.",
            "scope": "Global Workspace"
        },
        {
            "id": "disp_callback_03",
            "name": "Follow-Up Scheduled / Callback Requested",
            "code": "CALLBACK_REQUESTED",
            "category": "Callback / Follow-Up",
            "color": "#8B5CF6",
            "is_system": True,
            "auto_trigger": "Schedule automated callback dialer reminder",
            "sentiment": "Neutral (Needs Follow-Up)",
            "status": "Active",
            "description": "Prospect requested a callback at a specific date and time.",
            "scope": "Global Workspace"
        },
        {
            "id": "disp_voicemail_04",
            "name": "Voicemail Left / Machine Detected (AMD)",
            "code": "VOICEMAIL_LEFT",
            "category": "Unreached / Machine",
            "color": "#F59E0B",
            "is_system": True,
            "auto_trigger": "Queue automated retry attempt after 2 hours",
            "sentiment": "Neutral (Answering Machine)",
            "status": "Active",
            "description": "AI Agent detected answering machine audio and dropped a pre-recorded voicemail message.",
            "scope": "Global Workspace"
        },
        {
            "id": "disp_busy_05",
            "name": "Busy Line / User Engaged",
            "code": "LINE_BUSY",
            "category": "Unreached (Retry Required)",
            "color": "#EF4444",
            "is_system": True,
            "auto_trigger": "Immediate redial retry scheduled in 15 minutes",
            "sentiment": "Neutral (Line Engaged)",
            "status": "Active",
            "description": "Carrier returned SIP 486 Busy Here or line engaged signal.",
            "scope": "Global Workspace"
        },
        {
            "id": "disp_transfer_06",
            "name": "Transferred to Human Agent / Desk Phone",
            "code": "TRANSFERRED_TO_AGENT",
            "category": "Connected (Live Transfer)",
            "color": "#06B6D4",
            "is_system": True,
            "auto_trigger": "Log transfer duration and agent extension ID",
            "sentiment": "Positive / Escalated",
            "status": "Active",
            "description": "Caller requested live representative assistance; call transferred seamlessly via SIP/PSTN.",
            "scope": "Global Workspace"
        },
        {
            "id": "disp_dnc_07",
            "name": "Do-Not-Call (DNC) / Blacklist Request",
            "code": "DO_NOT_CALL_DNC",
            "category": "Compliance & Blacklist",
            "color": "#6B7280",
            "is_system": True,
            "auto_trigger": "Add phone number to global DNC blacklist immediately",
            "sentiment": "Negative / Opt-Out",
            "status": "Active",
            "description": "Caller opted out or requested removal; permanently suppressed from all future outbound campaigns.",
            "scope": "Global Workspace"
        }
    ]

    all_seed_categories = [
        ("telephony_providers", "Telephony Carriers", CARRIERS_DATA),
        ("sip_providers", "SIP Trunks & Private PBX", SIP_DATA),
        ("gsm_gateways", "SIM & GSM Gateways", GSM_DATA),
        ("call_routing", "Call Routing & Failover", ROUTING_DATA),
        ("dispositions", "Call Dispositions", DISPOSITIONS_DATA),
    ]

    # Clean wipe old records for all 5 telephony categories to guarantee 0 duplicates
    for cat_key, subtab_name, data_list in all_seed_categories:
        deleted = db.query(ProviderCredential).filter(
            ProviderCredential.organization_id == org_id,
            ProviderCredential.category == cat_key
        ).delete(synchronize_session=False)
        print(f"Purged {deleted} old records for category '{cat_key}'")

    db.commit()

    total_inserted = 0

    for cat_key, subtab_name, data_list in all_seed_categories:
        for item in data_list:
            p_name = item.get("name", "").lower().replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_")
            meta_json = json.dumps(item)
            new_cred = ProviderCredential(
                id=item["id"],
                organization_id=org_id,
                user_id=user_id,
                provider_name=p_name,
                category=cat_key,
                encrypted_key=encrypt_secret("config_rule"),
                plain_key=item.get("account_sid", item.get("port", "config_rule")),
                display_name=item.get("display_name", item.get("name")),
                base_url=item.get("base_url", item.get("sip_host", item.get("ip_host", ""))),
                primary_model=item.get("provider_type", item.get("device_type", "Standard")),
                selection_strategy="dynamic",
                api_version=item.get("api_version", "v1"),
                subtab_name=subtab_name,
                metadata_json=meta_json
            )
            db.add(new_cred)
            total_inserted += 1

    db.commit()
    db.close()
    print(f"Telephony seed completed: {total_inserted} fresh items cleanly inserted across 5 subtabs.")

if __name__ == "__main__":
    seed_telephony_providers()

