import { GLOBAL_COUNTRY_CODES_CATALOG } from '../data/globalLanguagesCatalog';

export const DEFAULT_BUSINESS_RULES_ITEMS: Record<string, any[]> = {
  business_types: [
    {
      id: 'bt_dental_01',
      name: 'Dental Clinic SSOT Rule',
      display_name: 'Dental Clinic & Orthodontics',
      category: 'Dental Clinic & Orthodontics',
      internal_code: 'BUS-DENT-01',
      description: 'Front desk patient appointment scheduling, insurance verification, and dental emergency triage.',
      default_ai_tone: 'Professional & Corporate',
      primary_behaviour: 'Appointment Based & Scheduling',
      default_greeting: 'Hello! Thank you for calling Nexus Dental Care. I am your AI assistant. How may I help you with your appointment or dental inquiry today?',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'bt_hospital_02',
      name: 'Hospital Care Management',
      display_name: 'Hospital & Multi-Specialty Healthcare',
      category: 'Hospital & Healthcare',
      internal_code: 'BUS-HOSP-02',
      description: 'Inpatient OPD booking, doctor round scheduling, and emergency room transfer protocol.',
      default_ai_tone: 'Empathetic & Support-Focused',
      primary_behaviour: 'Customer Support & Ticket Resolution',
      default_greeting: 'Thank you for calling Metro Healthcare Hospital. I am here to help you connect with your doctor or schedule an OPD consultation.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'bt_realestate_03',
      name: 'Real Estate Operations',
      display_name: 'Real Estate & Property Management',
      category: 'Real Estate & Property Management',
      internal_code: 'BUS-PROP-03',
      description: 'Lead qualification for property buyers, site visit scheduling, and mortgage inquiries.',
      default_ai_tone: 'Sales & Persuasive',
      primary_behaviour: 'Lead Generation & SDR Qualification',
      default_greeting: 'Hi there! Thank you for inquiring about our luxury residential projects. Are you looking to buy, rent, or schedule a private site visit?',
      status: 'Active',
      scope: 'Global Workspace'
    }
  ],
  departments: [
    {
      id: 'dept_sales_01',
      name: 'Inbound Sales & SDR',
      display_name: 'Inbound Sales & Lead Qualification',
      dept_type: 'Sales & Business Development',
      extension: '#101',
      queue_priority: 10,
      transfer_strategy: 'Round Robin (Equal Distribution)',
      overflow_department: 'Customer Support & Helpdesk',
      manager: 'Sarah Jenkins',
      description: 'Handles all incoming pre-sales inquiries, demo requests, and pricing negotiations.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'dept_support_02',
      name: 'Customer Support & FAQ',
      display_name: 'Customer Support Tier 1',
      dept_type: 'Customer Support & Helpdesk',
      extension: '#102',
      queue_priority: 20,
      transfer_strategy: 'Least Busy / Idle Time First',
      overflow_department: 'IT & Technical Operations',
      manager: 'David Miller',
      description: 'General inquiries, order status lookups, and account support.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'dept_billing_03',
      name: 'Billing & Invoicing Escalations',
      display_name: 'Billing & Accounts Team',
      dept_type: 'Billing & Invoicing',
      extension: '#103',
      queue_priority: 15,
      transfer_strategy: 'Sequential Extension Cascade',
      overflow_department: 'Executive Management & Suite',
      manager: 'Elena Rostova',
      description: 'Subscription upgrades, payment disputes, refunds, and invoice requests.',
      status: 'Active',
      scope: 'Global Workspace'
    }
  ],
  working_hours: [
    {
      id: 'wh_ist_01',
      name: 'Standard Business Hours (9AM - 6PM IST)',
      display_name: 'Standard Working Shift (India)',
      timezone: 'Asia/Kolkata (IST +05:30) - India',
      country: 'India',
      working_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      morning_shift: '09:00 AM - 01:00 PM',
      evening_shift: '02:00 PM - 06:00 PM',
      break_timing: '01:00 PM - 02:00 PM',
      is_247: false,
      after_hours_action: 'Voicemail Recording & AI Transcript',
      description: 'Standard 5-day enterprise operating shift with lunch break and voicemail failover.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'wh_247_02',
      name: '24/7 Emergency Support Hotline',
      display_name: '24/7 Continuous Helpline',
      timezone: 'America/New_York (EST -05:00) - US East Coast',
      country: 'Global',
      working_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      morning_shift: '00:00 AM - 12:00 PM',
      evening_shift: '12:00 PM - 11:59 PM',
      is_247: true,
      after_hours_action: 'AI Agent Autonomous Continue (24x7)',
      description: 'Non-stop 24/7 AI-powered hotline for emergency response and urgent caller triage.',
      status: 'Active',
      scope: 'Global Workspace'
    }
  ],
  languages: [
    {
      id: 'lang_hi_01',
      name: 'Hindi (India) - hi-IN',
      display_name: 'Hindi (India) Localization',
      locale: 'hi-IN',
      currency: 'INR (₹) - Indian Rupee',
      number_format: 'Indian Lakhs (1,00,000.00)',
      date_format: 'DD/MM/YYYY (UK/India/EU)',
      time_format: '12-Hour (AM/PM) e.g. 02:30 PM',
      telephone_format: '+91 (India PSTN)',
      fallback_language: 'English (United States)',
      description: 'Primary spoken language profile for Indian domestic campaigns with INR currency and Indian number formatting.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'lang_en_02',
      name: 'English (United States) - en-US',
      display_name: 'English (US) Localization',
      locale: 'en-US',
      currency: 'USD ($) - US Dollar',
      number_format: 'Standard Int. (1,000,000.00)',
      date_format: 'MM/DD/YYYY (US Format)',
      time_format: '12-Hour (AM/PM) e.g. 02:30 PM',
      telephone_format: '+1 (US & Canada NANP)',
      fallback_language: 'English (UK)',
      description: 'North American English localization with USD currency and US date conventions.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'lang_es_03',
      name: 'Spanish (Spain / LatAm) - es-ES',
      display_name: 'Spanish Localization',
      locale: 'es-ES',
      currency: 'EUR (€) - Euro',
      number_format: 'European Dot (1.000.000,00)',
      date_format: 'DD/MM/YYYY (UK/India/EU)',
      time_format: '24-Hour (Military) e.g. 14:30',
      telephone_format: '+34 (Spain PSTN)',
      fallback_language: 'English (United States)',
      description: 'Spanish international localization profile with Euro currency support.',
      status: 'Active',
      scope: 'Global Workspace'
    }
  ],
  country_codes: GLOBAL_COUNTRY_CODES_CATALOG.map((c: any) => ({
    id: c.id || `country_${c.iso2.toLowerCase()}`,
    name: `${c.name} (${c.dialCode})`,
    display_name: `${c.flag} ${c.name} (${c.dialCode})`,
    country_name: c.name,
    country: c.name,
    dial_code: c.dialCode,
    dialCode: c.dialCode,
    iso2: c.iso2,
    iso3: c.iso3,
    flag: c.flag,
    region: c.region,
    carrier_route: c.carrierRoute || 'Direct PSTN / GSM Route',
    description: `Official sovereign dial code for ${c.name} (${c.iso2}/${c.iso3}). Outbound E.164 cellular and PSTN trunk route.`,
    status: c.isActive ? 'Active' : 'Draft',
    scope: 'Global Workspace'
  })),
  business_policies: [
    {
      id: 'pol_hipaa_01',
      name: 'Strict Call Recording & HIPAA Compliance',
      display_name: 'HIPAA & 100% Call Recording Consent',
      policy_category: 'Privacy & Data Governance',
      policy_type: 'Mandatory (Strict Block)',
      severity: 'High (Critical Action)',
      execution_time: 'Before Call Connect',
      violation_action: 'Block Action Immediately',
      description: 'Ensures caller gives verbal or digital consent prior to recording any medical or sensitive information.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'pol_guard_02',
      name: 'Max Call Duration & Retries Guardrail',
      display_name: 'Call Duration & Auto-Retry Limit',
      policy_category: 'Escalation & Supervisor Takeover',
      policy_type: 'Optional (Advisory)',
      severity: 'Medium (Warning)',
      execution_time: 'During Live Call Stream',
      violation_action: 'Transfer to Human Supervisor',
      description: 'Caps single AI agent conversation duration to 15 minutes and max campaign attempts to 3 retries.',
      status: 'Active',
      scope: 'Global Workspace'
    },
    {
      id: 'pol_dnc_03',
      name: 'Anti-Spam & Do-Not-Call (DNC) Filter',
      display_name: 'DNC Compliance & Blacklist Guardrail',
      policy_category: 'Do Not Call (DNC) Registry',
      policy_type: 'Mandatory (Strict Block)',
      severity: 'High (Critical Action)',
      execution_time: 'Before Call Connect',
      violation_action: 'Block Action Immediately',
      description: 'Automatically blocks outbound dial attempts to numbers listed in national DNC registries.',
      status: 'Active',
      scope: 'Global Workspace'
    }
  ],
  telephony_providers: [
    {
      id: 'tel_twilio_01',
      name: 'Twilio Cloud Telephony',
      display_name: 'Twilio Primary Cloud Carrier',
      provider_type: 'Cloud Telephony',
      country: 'United States & Global (+1)',
      currency: 'USD ($)',
      status: 'Active',
      is_default: true,
      account_sid: 'ACa9b8c7d6e5f41234567890abcdef12',
      auth_token: '••••••••••••••••',
      base_url: 'https://api.twilio.com/2010-04-01',
      api_version: '2010-04-01',
      webhook_url: 'https://api.nexuscall.os/v1/webhooks/voice/twilio',
      pricing_mode: 'Paid',
      cost_per_min: '$0.014',
      inbound_cost: '$0.0085',
      did_monthly_cost: '$1.00',
      billing_interval: '60s/60s (Standard)',
      live_balance: '$142.50',
      latency: '18ms',
      sla_health: '99.99%',
      capabilities: { inbound: true, outbound: true, sms: true, mms: true, dtmf: true, recording: true, transfer: true, forwarding: true, conference: true, caller_id: true, sip: true },
      description: 'Tier-1 global voice carrier with elastic SIP trunking, call recording, and SMS delivery.',
      scope: 'Global Workspace'
    },
    {
      id: 'tel_telnyx_02',
      name: 'Telnyx Enterprise Voice',
      display_name: 'Telnyx High-Capacity Carrier',
      provider_type: 'Cloud Telephony',
      country: 'Global International PSTN',
      currency: 'USD ($)',
      status: 'Active',
      is_default: false,
      account_sid: 'KEY01829384756abcdef',
      auth_token: '••••••••••••••••',
      base_url: 'https://api.telnyx.com/v2',
      api_version: 'v2',
      webhook_url: 'https://api.nexuscall.os/v1/webhooks/voice/telnyx',
      pricing_mode: 'Paid',
      cost_per_min: '$0.007',
      inbound_cost: '$0.005',
      did_monthly_cost: '$0.85',
      billing_interval: '1s/1s (Per-Second)',
      live_balance: '$85.00',
      latency: '14ms',
      sla_health: '99.99%',
      capabilities: { inbound: true, outbound: true, sms: true, mms: true, dtmf: true, recording: true, transfer: true, forwarding: true, conference: true, caller_id: true, sip: true },
      description: 'Private global IP backbone delivering sub-15ms voice latency and wholesale DID inventory.',
      scope: 'Global Workspace'
    },
    {
      id: 'tel_plivo_03',
      name: 'Plivo Communications',
      display_name: 'Plivo Global Trunk',
      provider_type: 'Cloud Telephony',
      country: '190+ Countries Worldwide',
      currency: 'USD ($)',
      status: 'Active',
      is_default: false,
      account_sid: 'MA1928374650ABCDEF',
      auth_token: '••••••••••••••••',
      base_url: 'https://api.plivo.com/v1',
      api_version: 'v1',
      webhook_url: 'https://api.nexuscall.os/v1/webhooks/voice/plivo',
      pricing_mode: 'Paid',
      cost_per_min: '$0.012',
      inbound_cost: '$0.007',
      did_monthly_cost: '$0.90',
      billing_interval: '60s/60s (Standard)',
      live_balance: '$50.00',
      latency: '22ms',
      sla_health: '99.95%',
      capabilities: { inbound: true, outbound: true, sms: true, mms: false, dtmf: true, recording: true, transfer: true, forwarding: true, conference: true, caller_id: true, sip: true },
      description: 'Enterprise voice and messaging platform with redundant carrier failover.',
      scope: 'Global Workspace'
    }
  ],
  sip_providers: [
    {
      id: 'sip_twilio_01',
      preset_key: 'twilio_sip',
      name: 'Twilio Elastic SIP Trunk',
      display_name: 'Twilio Elastic SIP Trunk',
      carrier: 'Twilio Elastic SIP Infrastructure',
      direction: 'Bidirectional',
      sip_domain: 'nexus-enterprise.pstn.twilio.com',
      sip_host: 'nexus-enterprise.pstn.twilio.com',
      sip_port: '5060',
      transport: 'TLS Port 5061 (Encrypted)',
      outbound_proxy: '',
      username: 'nexus_sip_user_01',
      password: '••••••••••••••••',
      auth_mode: '🔑 SIP Digest Authentication (Username & Password)',
      registration_required: true,
      registration_expires: '3600s',
      registration_status: 'Registered (200 OK • 12ms)',
      ip_whitelist: '54.172.60.0/23, 54.244.51.0/24',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'SRTP Mandatory (AES-128-GCM)',
      cng_enabled: true,
      concurrent_calls: '1000 Channels',
      cps_rate_limit: '100 CPS',
      primary_carrier: 'Twilio Elastic SIP Infrastructure',
      secondary_carrier: 'Telnyx Private Cloud SIP Trunk',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'P-Asserted-Identity (PAI)',
      outbound_cli: '+1 (800) 555-0199',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'Enterprise TLS/SRTP encrypted SIP trunk connected to Twilio North American POP with sub-15ms latency.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_telnyx_02',
      preset_key: 'telnyx_sip',
      name: 'Telnyx Private Cloud SIP Trunk',
      display_name: 'Telnyx Direct Voice Route',
      carrier: 'Telnyx Global IP Backbone',
      direction: 'Bidirectional',
      sip_domain: 'sip.telnyx.com',
      sip_host: 'sip.telnyx.com',
      sip_port: '5060',
      transport: 'TLS Port 5061 (Encrypted)',
      outbound_proxy: '',
      username: 'telnyx_nexus_sip',
      password: '••••••••••••••••',
      auth_mode: 'IP Access Control List (ACL / Whitelisting)',
      registration_required: false,
      registration_expires: '3600s',
      registration_status: 'Connected (200 OK • 9ms)',
      ip_whitelist: '192.76.120.0/22, 64.16.224.0/19',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'SRTP Mandatory (AES-128-GCM)',
      cng_enabled: true,
      concurrent_calls: '1500 Channels',
      cps_rate_limit: '150 CPS',
      primary_carrier: 'Telnyx Global IP Backbone',
      secondary_carrier: 'Twilio Elastic SIP Trunk',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'P-Asserted-Identity (PAI)',
      outbound_cli: '+1 (888) 777-0122',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'Private-line wholesale SIP trunk with dedicated MPLS interconnect and ultra-low jitter.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_airtel_03',
      preset_key: 'airtel_sip',
      name: 'Bharti Airtel IQ Direct SIP Interconnect',
      display_name: 'Airtel IQ Enterprise PSTN Trunk',
      carrier: 'Bharti Airtel IQ',
      direction: 'Bidirectional',
      sip_domain: 'sip.airteliq.com',
      sip_host: 'sip.airteliq.com',
      sip_port: '5060',
      transport: 'UDP Port 5060 (Standard)',
      outbound_proxy: '',
      username: 'airtel_iq_nexus_01',
      password: '••••••••••••••••',
      auth_mode: 'IP Access Control List (ACL / Whitelisting)',
      registration_required: false,
      registration_expires: '3600s',
      registration_status: 'Registered (200 OK • 8ms)',
      ip_whitelist: '125.16.0.0/12, 182.79.0.0/16',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'Optional / Best-Effort',
      cng_enabled: true,
      concurrent_calls: '200 Channels',
      cps_rate_limit: '25 CPS',
      primary_carrier: 'Bharti Airtel IQ',
      secondary_carrier: 'Tata Smartflo (TTBS) Enterprise SIP',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'P-Asserted-Identity (PAI)',
      outbound_cli: '+91 11 4084 0000',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'Certified Indian telecom carrier direct interconnect with zero-hop local PSTN routing and DLT compliance.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_tata_04',
      preset_key: 'tata_sip',
      name: 'Tata Smartflo (TTBS) Enterprise SIP',
      display_name: 'Tata Smartflo Enterprise SIP',
      carrier: 'Tata Tele Business Services',
      direction: 'Bidirectional',
      sip_domain: 'sip.tatasmartflo.com',
      sip_host: 'sip.tatasmartflo.com',
      sip_port: '5060',
      transport: 'TLS Port 5061 (Encrypted)',
      outbound_proxy: '',
      username: 'ttbs_smartflo_trunk',
      password: '••••••••••••••••',
      auth_mode: 'IP Access Control List (ACL / Whitelisting)',
      registration_required: false,
      registration_expires: '3600s',
      registration_status: 'Registered (200 OK • 10ms)',
      ip_whitelist: '115.112.0.0/14, 121.240.0.0/13',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'SRTP Mandatory (AES-128-GCM)',
      cng_enabled: true,
      concurrent_calls: '300 Channels',
      cps_rate_limit: '30 CPS',
      primary_carrier: 'Tata Tele Business Services',
      secondary_carrier: 'Bharti Airtel IQ Direct SIP Interconnect',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'P-Asserted-Identity (PAI)',
      outbound_cli: '+91 22 6123 4567',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'Tata Tele Business Services cloud communication suite with enterprise DID bundles and high SLA uptime.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_jio_05',
      preset_key: 'jio_sip',
      name: 'Reliance Jio Enterprise SIP Trunk',
      display_name: 'Reliance Jio 5G Enterprise SIP',
      carrier: 'Reliance Jio Infocomm',
      direction: 'Bidirectional',
      sip_domain: 'ims.jio.com',
      sip_host: 'sip.enterprise.jio.com',
      sip_port: '5060',
      transport: 'UDP Port 5060 (Standard)',
      outbound_proxy: '',
      username: 'jio_ent_sip_01',
      password: '••••••••••••••••',
      auth_mode: 'IP Access Control List (ACL / Whitelisting)',
      registration_required: false,
      registration_expires: '3600s',
      registration_status: 'Registered (200 OK • 6ms)',
      ip_whitelist: '49.32.0.0/11, 157.32.0.0/11',
      codecs: '📱 AMR-WB 16kHz VoLTE + G.711a',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'Optional / Best-Effort',
      cng_enabled: true,
      concurrent_calls: '500 Channels',
      cps_rate_limit: '50 CPS',
      primary_carrier: 'Reliance Jio Infocomm',
      secondary_carrier: 'Bharti Airtel IQ Direct SIP Interconnect',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'P-Asserted-Identity (PAI)',
      outbound_cli: '+91 22 7960 0000',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'Native VoLTE and 5G NR voice interconnect across India with high packet delivery rate.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_freepbx_06',
      preset_key: 'freepbx_sip',
      name: 'FreePBX / Asterisk PBXact Softswitch',
      display_name: 'Internal FreePBX Softswitch',
      carrier: 'Internal PBX Server',
      direction: 'Bidirectional',
      sip_domain: 'pbx.local.internal',
      sip_host: '192.168.1.200',
      sip_port: '5060',
      transport: 'UDP Port 5060 (Standard)',
      outbound_proxy: '',
      username: 'nexus_pjsip_trunk',
      password: '••••••••••••••••',
      auth_mode: '🔑 SIP Digest Authentication (Username & Password)',
      registration_required: true,
      registration_expires: '600s (10 Mins)',
      registration_status: 'Registered (200 OK • 2ms)',
      ip_whitelist: '192.168.1.0/24, 10.0.0.0/16',
      codecs: '⚡ Opus Fullband + G.711 u-law',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'Optional / Best-Effort',
      cng_enabled: true,
      concurrent_calls: '100 Channels',
      cps_rate_limit: '20 CPS',
      primary_carrier: 'Internal PBX Server',
      secondary_carrier: 'Twilio Elastic SIP Trunk',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'Remote-Party-ID (RPID)',
      outbound_cli: '1001',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'Open-source Asterisk FreePBX server running on internal server hardware with zero per-minute costs.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_cisco_07',
      preset_key: 'cisco_sip',
      name: 'Cisco CUCM / CallManager Enterprise',
      display_name: 'Cisco CallManager Trunk',
      carrier: 'Cisco Enterprise Cluster',
      direction: 'Bidirectional',
      sip_domain: 'cucm.company.internal',
      sip_host: '10.0.10.100',
      sip_port: '5060',
      transport: 'TLS Port 5061 (Encrypted)',
      outbound_proxy: '',
      username: 'cisco_sip_profile',
      password: '••••••••••••••••',
      auth_mode: 'IP Access Control List (ACL / Whitelisting)',
      registration_required: false,
      registration_expires: '3600s',
      registration_status: 'Registered (200 OK • 4ms)',
      ip_whitelist: '10.0.10.0/24',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'SRTP Mandatory (AES-128-GCM)',
      cng_enabled: true,
      concurrent_calls: '500 Channels',
      cps_rate_limit: '40 CPS',
      primary_carrier: 'Cisco Enterprise Cluster',
      secondary_carrier: 'Twilio Elastic SIP Trunk',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'Remote-Party-ID (RPID)',
      outbound_cli: '+1 (800) 555-0100',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'Cisco Unified Communications Manager enterprise cluster SIP trunk connection.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_threecx_08',
      preset_key: 'threecx_sip',
      name: '3CX Phone System IP Gateway',
      display_name: '3CX VoIP Phone System',
      carrier: '3CX Cloud PBX',
      direction: 'Bidirectional',
      sip_domain: 'pbx.company.3cx.us',
      sip_host: 'pbx.company.3cx.us',
      sip_port: '5060',
      transport: 'UDP Port 5060 (Standard)',
      outbound_proxy: '',
      username: '3cx_trunk_100',
      password: '••••••••••••••••',
      auth_mode: '🔑 SIP Digest Authentication (Username & Password)',
      registration_required: true,
      registration_expires: '600s (10 Mins)',
      registration_status: 'Registered (200 OK • 14ms)',
      ip_whitelist: '0.0.0.0/0',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'Optional / Best-Effort',
      cng_enabled: true,
      concurrent_calls: '100 Channels',
      cps_rate_limit: '15 CPS',
      primary_carrier: '3CX Cloud PBX',
      secondary_carrier: 'Twilio Elastic SIP Trunk',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'P-Asserted-Identity (PAI)',
      outbound_cli: '+1 (800) 555-0300',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: '3CX IP-PBX Gateway trunk bridging AI Voice Agents to human softphone extensions.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_kamailio_09',
      preset_key: 'kamailio_sip',
      name: 'Kamailio Carrier-Grade SIP Proxy',
      display_name: 'Kamailio High-Throughput Proxy',
      carrier: 'Kamailio SBC Cluster',
      direction: 'Bidirectional',
      sip_domain: 'sbc.carrier.internal',
      sip_host: '10.0.4.150',
      sip_port: '5060',
      transport: 'UDP Port 5060 (Standard)',
      outbound_proxy: 'proxy.sbc.internal:5060',
      username: 'kamailio_admin',
      password: '••••••••••••••••',
      auth_mode: 'IP Access Control List (ACL / Whitelisting)',
      registration_required: false,
      registration_expires: '3600s',
      registration_status: 'Connected (200 OK • 1ms)',
      ip_whitelist: '10.0.4.0/24',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'Optional / Best-Effort',
      cng_enabled: true,
      concurrent_calls: '2000 Channels',
      cps_rate_limit: '200 CPS',
      primary_carrier: 'Kamailio SBC Cluster',
      secondary_carrier: 'Telnyx Private Cloud SIP Trunk',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'P-Asserted-Identity (PAI)',
      outbound_cli: '+1 (800) 555-0400',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'High-throughput Kamailio Session Border Controller handling hundreds of thousands of concurrent calls.',
      scope: 'Global Workspace'
    },
    {
      id: 'sip_freeswitch_10',
      preset_key: 'freeswitch_sip',
      name: 'FreeSWITCH Realtime Core Engine',
      display_name: 'FreeSWITCH Realtime Core Engine',
      carrier: 'FreeSWITCH Softswitch Cluster',
      direction: 'Bidirectional',
      sip_domain: 'fs.nexuscall.internal',
      sip_host: '10.0.4.160',
      sip_port: '5060',
      transport: 'TLS Port 5061 (Encrypted)',
      outbound_proxy: '',
      username: 'freeswitch_internal',
      password: '••••••••••••••••',
      auth_mode: '🔑 SIP Digest Authentication (Username & Password)',
      registration_required: true,
      registration_expires: '600s (10 Mins)',
      registration_status: 'Registered (200 OK • 2ms)',
      ip_whitelist: '10.0.4.0/24',
      codecs: '🎧 Opus HD + G.722 + PSTN',
      dtmf_mode: '🔢 RFC 2833 / RFC 4733 (RTP Events)',
      srtp: 'SRTP Mandatory (AES-128-GCM)',
      cng_enabled: true,
      concurrent_calls: '1000 Channels',
      cps_rate_limit: '100 CPS',
      primary_carrier: 'FreeSWITCH Softswitch Cluster',
      secondary_carrier: 'Twilio Elastic SIP Trunk',
      failover_enabled: true,
      failover_trigger: 'Immediate on SIP 5xx (500, 502, 503)',
      caller_id_header: 'Remote-Party-ID (RPID)',
      outbound_cli: '1002',
      nat_traversal: 'STUN/TURN Assisted (25s Keepalive)',
      status: 'Active',
      description: 'High-performance FreeSWITCH media engine cluster with real-time audio routing and DTMF dispatch.',
      scope: 'Global Workspace'
    }
  ],
  android_devices: [
    {
      id: 'dev_samsung_01',
      name: 'Samsung Galaxy S22 5G Gateway #1',
      display_name: 'Samsung Galaxy S22 5G (Hardware Node #1)',
      device_model: 'Samsung Galaxy S22 5G (SM-S901B)',
      android_version: 'Android 14 (One UI 6.1)',
      battery_level: '94% (Charging)',
      sim_slots: 2,
      sim1_carrier: 'Jio 5G True 5G (Unlimited Calls)',
      sim1_number: '+91 98765 43210',
      sim1_status: 'Ready (Connected)',
      sim2_carrier: 'Airtel 5G Plus (Unlimited Calls)',
      sim2_number: '+91 91234 56789',
      sim2_status: 'Ready (Connected)',
      signal_strength: '-72 dBm (Excellent)',
      latency: '24ms (Local Wi-Fi Bridge)',
      last_heartbeat: 'Just now (Realtime)',
      status: 'Online',
      description: 'Physical dual-SIM smartphone gateway executing zero-cost cellular PSTN calls via native Android bridge.',
      scope: 'Global Workspace'
    }
  ],
  gsm_gateways: [
    {
      id: 'gsm_dinstar_01',
      name: 'Dinstar UC2000-VG 8-Port GSM/VoLTE Gateway',
      display_name: 'Dinstar 8-Port Enterprise Gateway',
      hardware_model: 'Dinstar UC2000-VG-8G',
      firmware_version: 'v1.34.02',
      ports_count: 8,
      active_sims: 8,
      ip_address: '192.168.1.180:5060',
      sim_pool_name: 'India Domestic SIM Pool #1',
      supported_bands: '4G LTE FDD/TDD, 3G WCDMA, 2G GSM (900/1800MHz)',
      imei_rotation_enabled: true,
      imei_rotation_strategy: 'Auto-Rotate IMEI every 50 calls',
      sms_capabilities: true,
      ussd_balance_check: '*121# (Auto-Scheduled Daily)',
      total_minutes_routed: '14,820 Mins',
      status: 'Active',
      description: 'Rackmount 8-SIM cellular appliance with dynamic IMEI rotation, automated USSD recharge balance monitoring, and zero carrier per-minute fees.',
      scope: 'Global Workspace'
    }
  ],
  call_routing: [
    {
      id: 'route_least_cost_01',
      name: 'Smart Least-Cost Outbound Routing',
      display_name: 'Least-Cost Outbound Dial Plan',
      direction: 'Outbound',
      priority: '1',
      match_conditions: 'All Outbound Calling Campaigns • Domestic Numbers',
      primary_route: 'Samsung Galaxy S22 5G Gateway #1 (Free SIM)',
      secondary_route: 'Telnyx Elastic SIP Trunk ($0.007/min)',
      failover_strategy: 'Immediate on 5xx Error, SIM Busy, or Timeout (>4s)',
      cost_preference: 'Lowest Cost First (Zero-Charge SIM -> Cloud SIP)',
      status: 'Active',
      description: 'Automatically routes outbound calls through local Android SIM gateways first ($0.000 cost), falling back seamlessly to cloud SIP trunks if lines are occupied.',
      scope: 'Global Workspace'
    },
    {
      id: 'route_inbound_vip_02',
      name: 'Inbound VIP Support & DID Routing',
      display_name: 'Inbound Customer Routing Rule',
      direction: 'Inbound',
      priority: '1',
      match_conditions: 'All Inbound Toll-Free & DID Numbers • Business Hours',
      primary_route: 'Twilio Cloud Telephony',
      secondary_route: 'Direct SIP Interconnect (Twilio)',
      failover_strategy: 'Instant Failover on SIP 486 Busy / Trunk Congestion',
      cost_preference: 'Highest Quality & Audio Fidelity',
      status: 'Active',
      description: 'Dispatches incoming customer calls directly into AI Voice Agents with sub-100ms response latency and HD Opus audio.',
      scope: 'Global Workspace'
    },
    {
      id: 'route_emergency_03',
      name: 'Emergency Triage & After-Hours Cascade',
      display_name: '24/7 Escalation Routing',
      direction: 'Bidirectional',
      priority: '1',
      match_conditions: 'After-Hours Calls & Urgent Inquiries',
      primary_route: 'Twilio Cloud Telephony',
      secondary_route: 'Samsung Galaxy S22 5G Gateway #1',
      failover_strategy: 'Simultaneous Ring (Parallel Cascade)',
      cost_preference: 'Maximum Reliability / Zero Dropped Calls',
      status: 'Active',
      description: 'High-availability emergency routing rule ensuring 100% call delivery with dual-carrier parallel failover.',
      scope: 'Global Workspace'
    }
  ],
  dispositions: [
    {
      id: 'disp_booked_01',
      name: 'Appointment Booked & Confirmed',
      code: 'APPOINTMENT_BOOKED',
      category: 'Connected (Positive Outcome)',
      color: '#10B981',
      is_system: true,
      auto_trigger: 'Auto-sync to CRM Calendar & send SMS confirmation',
      sentiment: 'Positive (High Intent)',
      status: 'Active',
      description: 'Caller successfully scheduled and confirmed an appointment with the AI Voice Agent.',
      scope: 'Global Workspace'
    },
    {
      id: 'disp_interested_02',
      name: 'Connected & Interested (Hot Lead)',
      code: 'CONNECTED_HOT_LEAD',
      category: 'Connected (Sales Qualified)',
      color: '#3B82F6',
      is_system: true,
      auto_trigger: 'Assign high-priority lead to human SDR in CRM',
      sentiment: 'Positive (Warm Prospect)',
      status: 'Active',
      description: 'Prospect expressed strong purchase or booking interest; queued for priority follow-up.',
      scope: 'Global Workspace'
    },
    {
      id: 'disp_callback_03',
      name: 'Follow-Up Scheduled / Callback Requested',
      code: 'CALLBACK_REQUESTED',
      category: 'Callback / Follow-Up',
      color: '#8B5CF6',
      is_system: true,
      auto_trigger: 'Schedule automated callback dialer reminder',
      sentiment: 'Neutral (Needs Follow-Up)',
      status: 'Active',
      description: 'Prospect requested a callback at a specific date and time.',
      scope: 'Global Workspace'
    },
    {
      id: 'disp_voicemail_04',
      name: 'Voicemail Left / Machine Detected (AMD)',
      code: 'VOICEMAIL_LEFT',
      category: 'Unreached / Machine',
      color: '#F59E0B',
      is_system: true,
      auto_trigger: 'Queue automated retry attempt after 2 hours',
      sentiment: 'Neutral (Answering Machine)',
      status: 'Active',
      description: 'AI Agent detected answering machine audio and dropped a pre-recorded voicemail message.',
      scope: 'Global Workspace'
    },
    {
      id: 'disp_busy_05',
      name: 'Busy Line / User Engaged',
      code: 'LINE_BUSY',
      category: 'Unreached (Retry Required)',
      color: '#EF4444',
      is_system: true,
      auto_trigger: 'Immediate redial retry scheduled in 15 minutes',
      sentiment: 'Neutral (Line Engaged)',
      status: 'Active',
      description: 'Carrier returned SIP 486 Busy Here or line engaged signal.',
      scope: 'Global Workspace'
    },
    {
      id: 'disp_transfer_06',
      name: 'Transferred to Human Agent / Desk Phone',
      code: 'TRANSFERRED_TO_AGENT',
      category: 'Connected (Live Transfer)',
      color: '#06B6D4',
      is_system: true,
      auto_trigger: 'Log transfer duration and agent extension ID',
      sentiment: 'Positive / Escalated',
      status: 'Active',
      description: 'Caller requested live representative assistance; call transferred seamlessly via SIP/PSTN.',
      scope: 'Global Workspace'
    },
    {
      id: 'disp_dnc_07',
      name: 'Do-Not-Call (DNC) / Blacklist Request',
      code: 'DO_NOT_CALL_DNC',
      category: 'Compliance & Blacklist',
      color: '#6B7280',
      is_system: true,
      auto_trigger: 'Add phone number to global DNC blacklist immediately',
      sentiment: 'Negative / Opt-Out',
      status: 'Active',
      description: 'Caller opted out or requested removal; permanently suppressed from all future outbound campaigns.',
      scope: 'Global Workspace'
    }
  ]
};

export interface LlmProviderCatalogItem {
  provider: string;
  name: string;
  category: 'cloud' | 'local';
  group?: 'free_tier' | 'credits_low_cost' | 'frontier' | 'local';
  endpoint: string;
  getKeyUrl: string;
  docsUrl?: string;
  dashboardUrl?: string;
  defaultModel: string;
  apiVersion?: string;
  description?: string;
  pricingType?: string;
  contextWindow?: string;
  supportsStreaming?: boolean;
  supportsVision?: boolean;
  supportsFunctionCalling?: boolean;
  supportsJsonMode?: boolean;
  supportsRealtime?: boolean;
  supportsVoice?: boolean;
}

export const CLOUD_LLM_CATALOG: LlmProviderCatalogItem[] = [
  // 🟢 1. Free / Free-Tier Friendly Providers
  { provider: 'google', name: 'Google AI Studio / Gemini', category: 'cloud', group: 'free_tier', endpoint: 'https://generativelanguage.googleapis.com/v1beta', getKeyUrl: 'https://aistudio.google.com/app/apikey', docsUrl: 'https://ai.google.dev/docs', dashboardUrl: 'https://aistudio.google.com/', defaultModel: 'gemini-2.0-flash', pricingType: 'Free Tier Available (60 RPM)', contextWindow: '1M - 2M Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'groq', name: 'Groq Cloud', category: 'cloud', group: 'free_tier', endpoint: 'https://api.groq.com/openai/v1', getKeyUrl: 'https://console.groq.com/keys', docsUrl: 'https://console.groq.com/docs', dashboardUrl: 'https://console.groq.com/', defaultModel: 'llama-3.3-70b-versatile', pricingType: 'Generous Free Tier', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'cerebras', name: 'Cerebras Cloud', category: 'cloud', group: 'free_tier', endpoint: 'https://api.cerebras.ai/v1', getKeyUrl: 'https://cloud.cerebras.ai/', docsUrl: 'https://inference-docs.cerebras.ai/', dashboardUrl: 'https://cloud.cerebras.ai/', defaultModel: 'llama3.3-70b', pricingType: 'Free Tier (1M tokens/day)', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'sambanova', name: 'SambaNova Cloud', category: 'cloud', group: 'free_tier', endpoint: 'https://api.sambanova.ai/v1', getKeyUrl: 'https://cloud.sambanova.ai/apis', docsUrl: 'https://docs.sambanova.ai/', dashboardUrl: 'https://cloud.sambanova.ai/', defaultModel: 'Meta-Llama-3.3-70B-Instruct', pricingType: 'Free Tier Available', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'openrouter', name: 'OpenRouter', category: 'cloud', group: 'free_tier', endpoint: 'https://openrouter.ai/api/v1', getKeyUrl: 'https://openrouter.ai/keys', docsUrl: 'https://openrouter.ai/docs', dashboardUrl: 'https://openrouter.ai/', defaultModel: 'openrouter/auto', pricingType: 'Free & Low-Cost Routing', contextWindow: '128k - 2M Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'mistral', name: 'Mistral AI', category: 'cloud', group: 'free_tier', endpoint: 'https://api.mistral.ai/v1', getKeyUrl: 'https://console.mistral.ai/api-keys/', docsUrl: 'https://docs.mistral.ai/', dashboardUrl: 'https://console.mistral.ai/', defaultModel: 'mistral-large-latest', pricingType: 'Free Experimentation Tier', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'cohere', name: 'Cohere', category: 'cloud', group: 'free_tier', endpoint: 'https://api.cohere.com/v2', getKeyUrl: 'https://dashboard.cohere.com/api-keys', docsUrl: 'https://docs.cohere.com/', dashboardUrl: 'https://dashboard.cohere.com/', defaultModel: 'command-r-plus', pricingType: 'Free Trial API Key', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'cloudflare', name: 'Cloudflare Workers AI', category: 'cloud', group: 'free_tier', endpoint: 'https://api.cloudflare.com/client/v4/accounts/ai/v1', getKeyUrl: 'https://dash.cloudflare.com/profile/api-tokens', docsUrl: 'https://developers.cloudflare.com/workers-ai/', dashboardUrl: 'https://dash.cloudflare.com/', defaultModel: '@cf/meta/llama-3.3-70b-instruct', pricingType: '10,000 req/day Free', contextWindow: '64k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'github_models', name: 'GitHub Models / Azure AI', category: 'cloud', group: 'free_tier', endpoint: 'https://models.inference.ai.azure.com', getKeyUrl: 'https://github.com/settings/tokens', docsUrl: 'https://docs.github.com/en/github-models', dashboardUrl: 'https://github.com/marketplace/models', defaultModel: 'gpt-4o', pricingType: 'Free GitHub Tier', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'huggingface', name: 'Hugging Face Inference', category: 'cloud', group: 'free_tier', endpoint: 'https://api-inference.huggingface.co/v1', getKeyUrl: 'https://huggingface.co/settings/tokens', docsUrl: 'https://huggingface.co/docs/api-inference', dashboardUrl: 'https://huggingface.co/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Free Community Tier', contextWindow: '32k - 128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'nvidia', name: 'NVIDIA NIM / API', category: 'cloud', group: 'free_tier', endpoint: 'https://integrate.api.nvidia.com/v1', getKeyUrl: 'https://build.nvidia.com/explore/discover', docsUrl: 'https://docs.api.nvidia.com/', dashboardUrl: 'https://build.nvidia.com/', defaultModel: 'meta/llama-3.3-70b-instruct', pricingType: '1,000 Free Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'chutes', name: 'Chutes AI', category: 'cloud', group: 'free_tier', endpoint: 'https://llm.chutes.ai/v1', getKeyUrl: 'https://chutes.ai/app/keys', docsUrl: 'https://docs.chutes.ai/', dashboardUrl: 'https://chutes.ai/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Free Tier & Low Cost', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'deepinfra', name: 'DeepInfra', category: 'cloud', group: 'free_tier', endpoint: 'https://api.deepinfra.com/v1/openai', getKeyUrl: 'https://deepinfra.com/dash/api_keys', docsUrl: 'https://deepinfra.com/docs', dashboardUrl: 'https://deepinfra.com/dash', defaultModel: 'meta-llama/Meta-Llama-3.3-70B-Instruct', pricingType: 'Free Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },

  // 🟡 2. Trial / Low-Cost / Fast Cloud Providers
  { provider: 'together', name: 'Together AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.together.xyz/v1', getKeyUrl: 'https://api.together.ai/settings/api-keys', docsUrl: 'https://docs.together.ai/', dashboardUrl: 'https://api.together.xyz/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', pricingType: '$5-$25 Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'fireworks', name: 'Fireworks AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.fireworks.ai/inference/v1', getKeyUrl: 'https://fireworks.ai/account/api-keys', docsUrl: 'https://readme.fireworks.ai/', dashboardUrl: 'https://fireworks.ai/', defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct', pricingType: '$1 Free Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'deepseek', name: 'DeepSeek AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.deepseek.com/v1', getKeyUrl: 'https://platform.deepseek.com/api_keys', docsUrl: 'https://platform.deepseek.com/api-docs', dashboardUrl: 'https://platform.deepseek.com/', defaultModel: 'deepseek-chat', pricingType: 'Ultra Cheap Pay-As-You-Go', contextWindow: '64k - 128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'alibaba', name: 'Alibaba Cloud / Qwen', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1', getKeyUrl: 'https://dashscope.console.aliyun.com/apiKey', docsUrl: 'https://help.aliyun.com/document_detail/2712574.html', dashboardUrl: 'https://dashscope.console.aliyun.com/', defaultModel: 'qwen-plus', pricingType: 'Free Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'moonshot', name: 'Moonshot AI / Kimi', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.moonshot.cn/v1', getKeyUrl: 'https://platform.moonshot.cn/console/api-keys', docsUrl: 'https://platform.moonshot.cn/docs', dashboardUrl: 'https://platform.moonshot.cn/console', defaultModel: 'moonshot-v1-128k', pricingType: 'Free Trial Credits', contextWindow: '128k - 2M Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'minimax', name: 'MiniMax', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.minimaxi.chat/v1', getKeyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key', docsUrl: 'https://platform.minimaxi.com/document/fast_start', dashboardUrl: 'https://platform.minimaxi.com/', defaultModel: 'MiniMax-Text-01', pricingType: 'Free Trial Credits', contextWindow: '128k - 1M Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'perplexity', name: 'Perplexity AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.perplexity.ai', getKeyUrl: 'https://www.perplexity.ai/settings/api', docsUrl: 'https://docs.perplexity.ai/', dashboardUrl: 'https://www.perplexity.ai/', defaultModel: 'sonar-reasoning', pricingType: 'Pay-per-token API', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'ai21', name: 'AI21 Labs', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.ai21.com/v1', getKeyUrl: 'https://studio.ai21.com/account/api-key', docsUrl: 'https://docs.ai21.com/', dashboardUrl: 'https://studio.ai21.com/', defaultModel: 'jamba-1.5-large', pricingType: '$10 Free Trial Credits', contextWindow: '256k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'nebius', name: 'Nebius AI Studio', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.studio.nebius.ai/v1', getKeyUrl: 'https://studio.nebius.ai/settings/api-keys', docsUrl: 'https://docs.nebius.ai/', dashboardUrl: 'https://studio.nebius.ai/', defaultModel: 'meta-llama/Meta-Llama-3.3-70B-Instruct', pricingType: 'Trial Credits Available', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'novita', name: 'Novita AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.novita.ai/v3/openai', getKeyUrl: 'https://novita.ai/settings/key-management', docsUrl: 'https://novita.ai/docs', dashboardUrl: 'https://novita.ai/', defaultModel: 'meta-llama/llama-3.3-70b-instruct', pricingType: 'Free Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'siliconflow', name: 'SiliconFlow', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.siliconflow.cn/v1', getKeyUrl: 'https://cloud.siliconflow.cn/account/ak', docsUrl: 'https://docs.siliconflow.cn/', dashboardUrl: 'https://cloud.siliconflow.cn/', defaultModel: 'Qwen/Qwen2.5-72B-Instruct', pricingType: '20M Free Tokens', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'aiml_api', name: 'AIML API', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.aimlapi.com/v1', getKeyUrl: 'https://aimlapi.com/app/keys', docsUrl: 'https://docs.aimlapi.com/', dashboardUrl: 'https://aimlapi.com/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Free Trial Balance', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'portkey', name: 'Portkey AI Gateway', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.portkey.ai/v1', getKeyUrl: 'https://app.portkey.ai/', docsUrl: 'https://docs.portkey.ai/', dashboardUrl: 'https://app.portkey.ai/', defaultModel: 'gpt-4o', pricingType: 'Free Developer Plan', contextWindow: 'Multi-Provider', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'litellm', name: 'LiteLLM Proxy', category: 'cloud', group: 'credits_low_cost', endpoint: 'http://localhost:4000/v1', getKeyUrl: 'https://docs.litellm.ai/docs/proxy/quick_start', docsUrl: 'https://docs.litellm.ai/', dashboardUrl: 'http://localhost:4000/', defaultModel: 'gpt-4o', pricingType: 'Open Source & Hosted', contextWindow: 'Multi-Provider', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'featherless', name: 'Featherless AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.featherless.ai/v1', getKeyUrl: 'https://featherless.ai/keys', docsUrl: 'https://featherless.ai/docs', dashboardUrl: 'https://featherless.ai/', defaultModel: 'meta-llama/Meta-Llama-3.3-70B-Instruct', pricingType: 'Pay-per-token API', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'hyperbolic', name: 'Hyperbolic AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.hyperbolic.xyz/v1', getKeyUrl: 'https://app.hyperbolic.xyz/settings', docsUrl: 'https://docs.hyperbolic.xyz/', dashboardUrl: 'https://app.hyperbolic.xyz/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: '$10 Free Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'friendliai', name: 'FriendliAI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://inference.friendli.ai/v1', getKeyUrl: 'https://suite.friendli.ai/settings/tokens', docsUrl: 'https://docs.friendli.ai/', dashboardUrl: 'https://suite.friendli.ai/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Free Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'upstage', name: 'Upstage AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.upstage.ai/v1/solar', getKeyUrl: 'https://console.upstage.ai/api-keys', docsUrl: 'https://developers.upstage.ai/docs', dashboardUrl: 'https://console.upstage.ai/', defaultModel: 'solar-pro', pricingType: 'Free Trial Credits', contextWindow: '64k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'predibase', name: 'Predibase', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://serving.app.predibase.com/v1', getKeyUrl: 'https://app.predibase.com/settings/api-tokens', docsUrl: 'https://docs.predibase.com/', dashboardUrl: 'https://app.predibase.com/', defaultModel: 'llama-3-3-70b-instruct', pricingType: 'Free Developer Tier', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'lemonfox', name: 'Lemonfox AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.lemonfox.ai/v1', getKeyUrl: 'https://www.lemonfox.ai/dashboard', docsUrl: 'https://www.lemonfox.ai/docs', dashboardUrl: 'https://www.lemonfox.ai/', defaultModel: 'llama-3.3-70b-instruct', pricingType: 'Low Cost Pay-as-you-go', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'replicate', name: 'Replicate', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.replicate.com/v1', getKeyUrl: 'https://replicate.com/account/api-tokens', docsUrl: 'https://replicate.com/docs', dashboardUrl: 'https://replicate.com/', defaultModel: 'meta/meta-llama-3.3-70b-instruct', pricingType: 'Pay-per-second API', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'anyscale', name: 'Anyscale Endpoints', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.endpoints.anyscale.com/v1', getKeyUrl: 'https://app.endpoints.anyscale.com/credentials', docsUrl: 'https://docs.endpoints.anyscale.com/', dashboardUrl: 'https://app.endpoints.anyscale.com/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'modal', name: 'Modal Labs', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.modal.com/v1', getKeyUrl: 'https://modal.com/settings', docsUrl: 'https://modal.com/docs', dashboardUrl: 'https://modal.com/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: '$30/mo Free Compute', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'baseten', name: 'Baseten', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://model-api.baseten.co/v1', getKeyUrl: 'https://app.baseten.co/settings/api_keys', docsUrl: 'https://docs.baseten.co/', dashboardUrl: 'https://app.baseten.co/', defaultModel: 'llama-3.3-70b-instruct', pricingType: '$30 Free Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'runpod', name: 'RunPod Serverless', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.runpod.ai/v2', getKeyUrl: 'https://www.runpod.io/console/serverless/user/settings', docsUrl: 'https://docs.runpod.io/', dashboardUrl: 'https://www.runpod.io/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Pay-as-you-go GPU', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'lambda', name: 'Lambda Cloud', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.lambdalabs.com/v1', getKeyUrl: 'https://cloud.lambdalabs.com/api-keys', docsUrl: 'https://docs.lambdalabs.com/', dashboardUrl: 'https://cloud.lambdalabs.com/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Pay-per-hour GPU', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'digitalocean', name: 'DigitalOcean Gradient AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.digitalocean.com/v2/ai/openai', getKeyUrl: 'https://cloud.digitalocean.com/account/api/tokens', docsUrl: 'https://docs.digitalocean.com/products/gradient/', dashboardUrl: 'https://cloud.digitalocean.com/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: '$200 Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'nscale', name: 'Nscale Cloud AI', category: 'cloud', group: 'credits_low_cost', endpoint: 'https://api.nscale.com/v1', getKeyUrl: 'https://nscale.com/', docsUrl: 'https://docs.nscale.com/', dashboardUrl: 'https://nscale.com/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: 'Cloud Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'vercel_ai', name: 'Vercel AI Gateway', category: 'cloud', group: 'free_tier', endpoint: 'https://api.gateway.ai.cloudflare.com/v1', getKeyUrl: 'https://vercel.com/account/tokens', docsUrl: 'https://sdk.vercel.ai/docs', dashboardUrl: 'https://vercel.com/', defaultModel: 'gpt-4o', pricingType: 'Free Hobby Tier', contextWindow: 'Multi-Provider', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },

  // 🔵 3. Major Frontier & Proprietary Labs
  { provider: 'openai', name: 'OpenAI', category: 'cloud', group: 'frontier', endpoint: 'https://api.openai.com/v1', getKeyUrl: 'https://platform.openai.com/api-keys', docsUrl: 'https://platform.openai.com/docs', dashboardUrl: 'https://platform.openai.com/', defaultModel: 'gpt-4o', pricingType: 'Pay-per-token API', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'anthropic', name: 'Anthropic (Claude)', category: 'cloud', group: 'frontier', endpoint: 'https://api.anthropic.com/v1', getKeyUrl: 'https://console.anthropic.com/settings/keys', docsUrl: 'https://docs.anthropic.com/', dashboardUrl: 'https://console.anthropic.com/', defaultModel: 'claude-3-5-sonnet-20241022', pricingType: 'Pay-per-token API', contextWindow: 'Claude 3.7 Sonnet / 3.5 Sonnet / Haiku (200k)', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'xai', name: 'xAI (Grok)', category: 'cloud', group: 'frontier', endpoint: 'https://api.x.ai/v1', getKeyUrl: 'https://console.x.ai/', docsUrl: 'https://docs.x.ai/', dashboardUrl: 'https://console.x.ai/', defaultModel: 'grok-2-latest', pricingType: '$25/mo Tier / Pay-per-token', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'azure_openai', name: 'Azure OpenAI / AI Foundry', category: 'cloud', group: 'frontier', endpoint: 'https://YOUR_RESOURCE.openai.azure.com/v1', getKeyUrl: 'https://portal.azure.com/', docsUrl: 'https://learn.microsoft.com/azure/ai-services/openai/', dashboardUrl: 'https://portal.azure.com/', defaultModel: 'gpt-4o', pricingType: 'Enterprise Azure Billing', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'aws_bedrock', name: 'AWS Bedrock', category: 'cloud', group: 'frontier', endpoint: 'https://bedrock-runtime.us-east-1.amazonaws.com', getKeyUrl: 'https://console.aws.amazon.com/bedrock/', docsUrl: 'https://docs.aws.amazon.com/bedrock/', dashboardUrl: 'https://console.aws.amazon.com/bedrock/', defaultModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0', pricingType: 'AWS Cloud Billing', contextWindow: '200k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'google_vertex', name: 'Google Vertex AI', category: 'cloud', group: 'frontier', endpoint: 'https://us-central1-aiplatform.googleapis.com/v1', getKeyUrl: 'https://console.cloud.google.com/vertex-ai', docsUrl: 'https://cloud.google.com/vertex-ai/docs', dashboardUrl: 'https://console.cloud.google.com/vertex-ai', defaultModel: 'gemini-1.5-pro', pricingType: 'Google Cloud Billing', contextWindow: '1M - 2M Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'ibm_watsonx', name: 'IBM watsonx.ai', category: 'cloud', group: 'frontier', endpoint: 'https://us-south.ml.cloud.ibm.com/ml/v1', getKeyUrl: 'https://cloud.ibm.com/iam/apikeys', docsUrl: 'https://dataplatform.cloud.ibm.com/docs', dashboardUrl: 'https://cloud.ibm.com/watsonx', defaultModel: 'ibm/granite-13b-chat-v2', pricingType: 'Enterprise IBM Cloud', contextWindow: '128k Tokens', supportsStreaming: true, supportsVoice: false, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'oracle_ai', name: 'Oracle Cloud Generative AI', category: 'cloud', group: 'frontier', endpoint: 'https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130', getKeyUrl: 'https://cloud.oracle.com/', docsUrl: 'https://docs.oracle.com/en-us/iaas/Content/generative-ai/overview.htm', dashboardUrl: 'https://cloud.oracle.com/', defaultModel: 'cohere.command-r-plus-08-2024', pricingType: 'Oracle Cloud Billing', contextWindow: '128k Tokens', supportsStreaming: true, supportsVoice: false, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'databricks', name: 'Databricks Mosaic AI', category: 'cloud', group: 'frontier', endpoint: 'https://databricks.com/serving-endpoints', getKeyUrl: 'https://databricks.com/', docsUrl: 'https://docs.databricks.com/en/generative-ai/generative-ai.html', dashboardUrl: 'https://databricks.com/', defaultModel: 'databricks-dbrx-instruct', pricingType: 'Databricks DBUs', contextWindow: '128k Tokens', supportsStreaming: true, supportsVoice: false, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'snowflake', name: 'Snowflake Cortex AI', category: 'cloud', group: 'frontier', endpoint: 'https://snowflake.com/cortex/inference', getKeyUrl: 'https://snowflake.com/', docsUrl: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/llm-functions', dashboardUrl: 'https://snowflake.com/', defaultModel: 'snowflake-arctic', pricingType: 'Snowflake Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVoice: false, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'writer', name: 'Writer Palmyra', category: 'cloud', group: 'frontier', endpoint: 'https://api.writer.com/v1', getKeyUrl: 'https://app.writer.com/admin/api-keys', docsUrl: 'https://dev.writer.com/', dashboardUrl: 'https://app.writer.com/', defaultModel: 'palmyra-x-004', pricingType: 'Enterprise Tier', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'aleph_alpha', name: 'Aleph Alpha', category: 'cloud', group: 'frontier', endpoint: 'https://api.aleph-alpha.com', getKeyUrl: 'https://app.aleph-alpha.com/keys', docsUrl: 'https://docs.aleph-alpha.com/', dashboardUrl: 'https://app.aleph-alpha.com/', defaultModel: 'luminous-extended', pricingType: 'Pay-per-token API', contextWindow: '64k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'zhipu', name: 'Zhipu AI (GLM)', category: 'cloud', group: 'frontier', endpoint: 'https://open.bigmodel.cn/api/paas/v4', getKeyUrl: 'https://open.bigmodel.cn/usercenter/apikeys', docsUrl: 'https://open.bigmodel.cn/dev/api', dashboardUrl: 'https://open.bigmodel.cn/', defaultModel: 'glm-4', pricingType: 'Free Trial Credits', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: '01_ai', name: '01.AI (Yi)', category: 'cloud', group: 'frontier', endpoint: 'https://api.01.ai/v1', getKeyUrl: 'https://platform.01.ai/api-keys', docsUrl: 'https://platform.01.ai/docs', dashboardUrl: 'https://platform.01.ai/', defaultModel: 'yi-lightning', pricingType: 'Trial Balance', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'tencent_hunyuan', name: 'Tencent Hunyuan', category: 'cloud', group: 'frontier', endpoint: 'https://hunyuan.tencentcloudapi.com/', getKeyUrl: 'https://console.cloud.tencent.com/hunyuan', docsUrl: 'https://cloud.tencent.com/document/product/1729', dashboardUrl: 'https://console.cloud.tencent.com/', defaultModel: 'hunyuan-large', pricingType: 'Free Trial Credits', contextWindow: '256k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'baidu_qianfan', name: 'Baidu Qianfan / ERNIE', category: 'cloud', group: 'frontier', endpoint: 'https://aip.baidubce.com/v2', getKeyUrl: 'https://console.bce.baidu.com/qianfan/ais/console/onlineService', docsUrl: 'https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html', dashboardUrl: 'https://console.bce.baidu.com/', defaultModel: 'ernie-4.0-turbo-8k', pricingType: 'Free Trial Quota', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: false },
  { provider: 'bytedance_doubao', name: 'ByteDance Doubao', category: 'cloud', group: 'frontier', endpoint: 'https://ark.cn-beijing.volces.com/api/v3', getKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey', docsUrl: 'https://www.volcengine.com/docs/82379/1099475', dashboardUrl: 'https://console.volcengine.com/ark', defaultModel: 'doubao-pro-32k', pricingType: '500k Free Tokens', contextWindow: '128k Tokens', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true }
];

export const LOCAL_LLM_CATALOG: LlmProviderCatalogItem[] = [
  { provider: 'ollama', name: 'Ollama Server', category: 'local', group: 'local', endpoint: 'http://localhost:11434', getKeyUrl: 'https://ollama.com/', docsUrl: 'https://github.com/ollama/ollama', dashboardUrl: 'http://localhost:11434/', defaultModel: 'llama3.3:latest', pricingType: '100% Free & Local', contextWindow: 'Configurable (32k-128k)', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'lmstudio', name: 'LM Studio', category: 'local', group: 'local', endpoint: 'http://localhost:1234/v1', getKeyUrl: 'https://lmstudio.ai/', docsUrl: 'https://lmstudio.ai/docs', dashboardUrl: 'http://localhost:1234/', defaultModel: 'local-model', pricingType: '100% Free & Local', contextWindow: 'Local GPU/CPU', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'vllm', name: 'vLLM Server', category: 'local', group: 'local', endpoint: 'http://localhost:8000/v1', getKeyUrl: 'https://github.com/vllm-project/vllm', docsUrl: 'https://docs.vllm.ai/', dashboardUrl: 'http://localhost:8000/', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', pricingType: '100% Free & Local', contextWindow: 'Local GPU', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'localai', name: 'LocalAI Engine', category: 'local', group: 'local', endpoint: 'http://localhost:8080/v1', getKeyUrl: 'https://localai.io/', docsUrl: 'https://localai.io/basics/getting_started/', dashboardUrl: 'http://localhost:8080/', defaultModel: 'gpt-4', pricingType: '100% Free & Local', contextWindow: 'Local CPU/GPU', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'textgen_webui', name: 'TextGen WebUI', category: 'local', group: 'local', endpoint: 'http://localhost:5000/v1', getKeyUrl: 'https://github.com/oobabooga/text-generation-webui', docsUrl: 'https://github.com/oobabooga/text-generation-webui', dashboardUrl: 'http://localhost:5000/', defaultModel: 'local-model', pricingType: '100% Free & Local', contextWindow: 'Local GPU', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'jan', name: 'Jan.ai Local Server', category: 'local', group: 'local', endpoint: 'http://localhost:1337/v1', getKeyUrl: 'https://jan.ai/', docsUrl: 'https://jan.ai/docs', dashboardUrl: 'http://localhost:1337/', defaultModel: 'local-model', pricingType: '100% Free & Local', contextWindow: 'Local Hardware', supportsStreaming: true, supportsVision: false, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true },
  { provider: 'openai_compatible', name: 'Custom OpenAI-Compatible', category: 'local', group: 'local', endpoint: 'http://localhost:8000/v1', getKeyUrl: '', docsUrl: 'https://platform.openai.com/docs/api-reference', dashboardUrl: 'http://localhost:8000/', defaultModel: 'custom-model', pricingType: 'Custom Endpoint', contextWindow: 'Dynamic', supportsStreaming: true, supportsVision: true, supportsFunctionCalling: true, supportsJsonMode: true, supportsRealtime: true }
];

export const LLM_CATALOG = [...CLOUD_LLM_CATALOG, ...LOCAL_LLM_CATALOG];

