import React, { useState } from 'react';
import { Bell, Check, Trash2, Search, Filter, PhoneCall, Zap, ShieldAlert, CreditCard, Eye } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Input } from '../components/ui/Input';
import { Tabs } from '../components/ui/Tabs';
import { useToast } from '../components/ui/Toast';

interface NotificationItem {
  id: string;
  title: string;
  desc: string;
  time: string;
  category: 'telephony' | 'calls' | 'system' | 'billing' | 'security';
  read: boolean;
  actionLabel?: string;
  actionUrl?: string;
}

export const NotificationsView: React.FC = () => {
  const [activeTab, setActiveTab] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 5;

  const [notifications, setNotifications] = useState<NotificationItem[]>([
    {
      id: 'n1',
      title: 'High Call Volume Burst Detected',
      desc: 'Campaign Q3 Outbound Blast reached 85% concurrent line capacity.',
      time: '2 mins ago',
      category: 'telephony',
      read: false,
      actionLabel: 'View Trunking',
    },
    {
      id: 'n2',
      title: 'Demo Scheduled by Agent Sophia',
      desc: 'David Miller (Acme Corp) scheduled a 20-min demo for Thursday 2:00 PM EST.',
      time: '12 mins ago',
      category: 'calls',
      read: false,
      actionLabel: 'View Call Log',
    },
    {
      id: 'n3',
      title: 'Knowledge Base Vector Index Synced',
      desc: 'Docs auto-indexer finished parsing 420 vector chunks from Manual v4.2.pdf.',
      time: '1 hour ago',
      category: 'system',
      read: true,
      actionLabel: 'Inspect Embeddings',
    },
    {
      id: 'n4',
      title: 'Monthly Usage Invoice Generated',
      desc: 'Invoice #inv_8801 for $899.00 is ready for PDF download.',
      time: '3 hours ago',
      category: 'billing',
      read: false,
      actionLabel: 'Download Invoice',
    },
    {
      id: 'n5',
      title: 'New API Key Provisioned',
      desc: 'Production API key generated by Alex Vance.',
      time: '1 day ago',
      category: 'security',
      read: true,
      actionLabel: 'Security Audit',
    },
    {
      id: 'n6',
      title: 'Negative Sentiment Escalation',
      desc: 'Customer in Call #8013 flagged high frustration during return policy inquiry.',
      time: '2 days ago',
      category: 'calls',
      read: true,
      actionLabel: 'Listen to Call',
    },
  ]);

  const { addToast } = useToast();

  const handleMarkAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
    addToast({
      type: 'info',
      title: 'Notifications Cleared',
      description: 'All pending unread notifications marked as read.',
    });
  };

  const handleToggleRead = (id: string) => {
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, read: !n.read } : n))
    );
  };

  const handleDelete = (id: string, title: string) => {
    setNotifications((prev) => prev.filter((n) => n.id !== id));
    addToast({
      type: 'info',
      title: 'Notification Dismissed',
      description: `Removed "${title}".`,
    });
  };

  const handleActionClick = (n: NotificationItem) => {
    addToast({
      type: 'info',
      title: n.title,
      description: `Navigating to action module for "${n.actionLabel}".`,
    });
  };

  const filtered = notifications.filter((n) => {
    const matchesTab = activeTab === 'all' || n.category === activeTab;
    const matchesQuery =
      n.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      n.desc.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesTab && matchesQuery;
  });

  const totalPages = Math.ceil(filtered.length / pageSize) || 1;
  const paginated = filtered.slice((page - 1) * pageSize, page * pageSize);
  const unreadCount = notifications.filter((n) => !n.read).length;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
            Notification Center
          </h2>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">
            Realtime alerts covering call completions, trunk capacity, and vector index syncs.
          </p>
        </div>
        <Button variant="outline" onClick={handleMarkAllRead} leftIcon={<Check className="h-4 w-4" />}>
          Mark All Read ({unreadCount})
        </Button>
      </div>

      <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
        <Tabs
          activeTab={activeTab}
          onChange={(tab) => {
            setActiveTab(tab);
            setPage(1);
          }}
          variant="pills"
          tabs={[
            { id: 'all', label: 'All Alerts', badge: notifications.length },
            { id: 'calls', label: 'AI Calls' },
            { id: 'telephony', label: 'Telephony' },
            { id: 'system', label: 'System' },
            { id: 'billing', label: 'Billing' },
            { id: 'security', label: 'Security' },
          ]}
        />
        <div className="w-full sm:w-64">
          <Input
            placeholder="Search alerts..."
            leftIcon={<Search className="h-3.5 w-3.5" />}
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
      </div>

      <Card>
        <CardContent className="p-0 divide-y divide-zinc-100 dark:divide-zinc-800">
          {paginated.length === 0 ? (
            <div className="p-8 text-center text-xs text-zinc-500">
              No notifications matching current filters.
            </div>
          ) : (
            paginated.map((n) => {
              const iconMap = {
                telephony: <Zap className="h-4 w-4 text-amber-500" />,
                calls: <PhoneCall className="h-4 w-4 text-blue-500" />,
                system: <Bell className="h-4 w-4 text-emerald-500" />,
                billing: <CreditCard className="h-4 w-4 text-purple-500" />,
                security: <ShieldAlert className="h-4 w-4 text-red-500" />,
              };

              return (
                <div
                  key={n.id}
                  className={`p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 transition-colors ${
                    !n.read ? 'bg-blue-50/30 dark:bg-blue-950/20' : 'hover:bg-zinc-50 dark:hover:bg-zinc-900/50'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <div className="mt-0.5 p-2 rounded-lg bg-zinc-100 dark:bg-zinc-800 shrink-0">
                      {iconMap[n.category]}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className={`text-xs font-semibold ${!n.read ? 'text-zinc-900 dark:text-zinc-100' : 'text-zinc-600 dark:text-zinc-400'}`}>
                          {n.title}
                        </h4>
                        {!n.read && <Badge variant="primary" size="sm">New</Badge>}
                      </div>
                      <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">{n.desc}</p>
                      <span className="text-[10px] text-zinc-400 mt-1 block">{n.time}</span>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                    {n.actionLabel && (
                      <Button size="sm" variant="outline" onClick={() => handleActionClick(n)} leftIcon={<Eye className="h-3.5 w-3.5" />}>
                        {n.actionLabel}
                      </Button>
                    )}
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => handleToggleRead(n.id)}
                    >
                      {n.read ? 'Mark Unread' : 'Mark Read'}
                    </Button>
                    <Button
                      size="sm"
                      variant="danger"
                      leftIcon={<Trash2 className="h-3.5 w-3.5" />}
                      onClick={() => handleDelete(n.id, n.title)}
                    />
                  </div>
                </div>
              );
            })
          )}
        </CardContent>

        {/* Pagination Footer */}
        {totalPages > 1 && (
          <div className="p-3 border-t border-zinc-100 dark:border-zinc-800 flex items-center justify-between text-xs text-zinc-500">
            <span>
              Page {page} of {totalPages}
            </span>
            <div className="flex items-center gap-2">
              <Button size="sm" variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>
                Previous
              </Button>
              <Button size="sm" variant="outline" disabled={page === totalPages} onClick={() => setPage(page + 1)}>
                Next
              </Button>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
};
